### ISSUE TITLE
Style not apply

### ISSUE THREAD

**Issue by JeremyGerard** [yaminncco/vue-sidebar-menu#1]
Hi,

First of all, nice work !
However i don't have your style ...
Do you know why ?

![capturesidebarmenu](https://user-images.githubusercontent.com/4650308/47792538-85e4fe80-dd1c-11e8-85ac-23577e0daae7.PNG)

**Comment by yaminncco** [comment]
what browser? it looks like compatibility issues

**Comment by JeremyGerard** [comment]
Hi,

I'm using Chrome 70.0.35.38.77
But it the same on Firefox. Maybe i forgot to configure something. Do you have an idea about that ?

**Comment by yaminncco** [comment]
try the new update if issue still persist open the developer tools and see what styles are not working

**Comment by dflourusso** [comment]
I solved it by using `!important`

**Comment by yaminncco** [comment]
I think this issue is related to #5, Will close this.
