### ISSUE TITLE
Phone/tablet select issue

### ISSUE THREAD

**Issue by emilhein** [yaminncco/vue-sidebar-menu#10]
Hi,

great plugin by the way. 
There is a issue on mobile/tablet when you click a menu item (its stays active).

To reproduce:
1. Open the demo example in Chrome
2. In dev tools toggle the device toolbar and select a Iphone or Ipad. 
3. Pres a menu link.

![image](https://user-images.githubusercontent.com/3637557/48900050-9850e480-ee51-11e8-9beb-1d4f5d346a29.png)

Best regards

**Comment by yaminncco** [comment]
Hi, this is how it works on mobile devices: the menu item will open and close (click outside) on the click event, because hover on a touchscreen doesn't work the same on the desktop.
Thanks.

**Comment by emilhein** [comment]
Thats true. But seen from the user i doesnt make sense that the menu stays open aften you press. Maybe there could be a timeout that would close it after x seconds?

**Comment by yaminncco** [comment]
in  v2.3.1 the item will close after some delay

**Comment by emilhein** [comment]
I can confirm it works. Thanks for the quick response

**Comment by myelement88** [comment]
Really good work with the sidebar. And in general it works like a charm.

But on mobile I'm running into the same issues as already described: the sidebar stays open. It only closes if I click on a button or an image. 

Currently tested with version 3.6.2 on iPhone SE (really small viewport) with Chrome/Firefox/Safari. I will try it later also on Android devices.
