### ISSUE TITLE
Move toggle button to top rather than bottom

### ISSUE THREAD

**Issue by maxanstey** [yaminncco/vue-sidebar-menu#100]
Sorry for the simple question.. is it possible to move the position of the toggle button from the bottom to the top? Thanks

**Comment by yaminncco** [comment]
with CSS you can use flexbox `order` property:
```
.v-sidebar-menu .vsm--toggle-btn {
  order: -1;
}
```

**Comment by maxanstey** [comment]
Great, thank you! @yaminncco
