### ISSUE TITLE
Show icon for component items

### ISSUE THREAD

**Issue by srinivas146** [yaminncco/vue-sidebar-menu#101]

**Comment by srinivas146** [comment]
Hi, Is it possible to show icon for components, when side bar is collapsed ??

**Comment by yaminncco** [comment]
you can pass collapsed value as a prop through `props` property then in the component use conditional rendering

```
{
    component: componentName,
    props: componentProps
}
```

**Comment by srinivas146** [comment]
how can i listen for the events emitted from the components from the sidebar ?

**Comment by yaminncco** [comment]
check [events](https://github.com/yaminncco/vue-sidebar-menu#events)
