### ISSUE TITLE
How to add <hr> between sections

### ISSUE THREAD

**Issue by stefanknegt** [yaminncco/vue-sidebar-menu#102]
In the demo on https://yaminncco.github.io/vue-sidebar-menu/#/events there is a HR between the usage and example section. How can you add this?

**Comment by yaminncco** [comment]
you can make custom item using component property, check [demo](https://github.com/yaminncco/vue-sidebar-menu/blob/master/demo/App.vue#L91)

**Comment by stefanknegt** [comment]
Thanks, but is there no way to do this when using the runtime-only build of Vue?

**Comment by yaminncco** [comment]
you can use render function

```
const separator = {
  render (h) {
    return h('hr', {
      style: {
        borderColor: 'rgba(0, 0, 0, 0.1)',
        margin: '20px'
      }
    })
  }
}
```
