### ISSUE TITLE
No possibility to expand item programmatically

### ISSUE THREAD

**Issue by kiril-malyhin** [yaminncco/vue-sidebar-menu#104]
Hi,
I'm stuck with possibility to expand all items, if sub-item is selected.

Desired state: 
![image](https://user-images.githubusercontent.com/11473999/71463816-b2819280-27c8-11ea-9a1a-6360f76b38b0.png)

Actual state: sub-item on 3-rd level is selected. After page reload tree is not expanded properly to selected item.
![image](https://user-images.githubusercontent.com/11473999/71463868-d349e800-27c8-11ea-8f58-fe42c031354c.png)

Is it possible to set some flag to parent of selected item, that it should be expanded?

Thx in advance!

**Comment by yaminncco** [comment]
active item should auto open on reload, can you make a reproduction

**Comment by kiril-malyhin** [comment]
@yaminncco , can you, please, explain, how you determine 'activity' of the page? Maybe it is related to some classes? I'm asking, because I add some classes based on my rules, maybe it broke something. Thx!

**Comment by kiril-malyhin** [comment]
@yaminncco , fixed with adding additional prop exactPath
