### ISSUE TITLE
list/item/icon custom class property?

### ISSUE THREAD

**Issue by gtzures** [yaminncco/vue-sidebar-menu#105]
What is the correct way to customize the style of the list/item/icon?

I can't get `.v-sidebar-menu .vsm--list` (or the other corresponding documented classes) to work.

**Comment by yaminncco** [comment]
you may need to increase specificity like adding a new class to the component

`.sidebar.v-sidebar-menu .vsm--list {}`

**Comment by gtzures** [comment]
Thanks for the quick response, and for the awesome work on this ;)
But adding a new class didn't do the trick.

I forgot to mention, that the top level class style DOES work - `.v-sidebar-menu` - until I added specificity to it like `.sidebar .v-sidebar-menu`. That is the only class style that had any affect.

Here is my code:

```
<template>
    <sidebar-menu class="sidebar" :menu="menu" hideToggle disableHover/>
</template>

<script>
import { SidebarMenu } from 'vue-sidebar-menu';

export default {
    components: {
        SidebarMenu,
    },
    data() {
        return {
            menu: [
                {
                    href: '/clients',
                    title: 'My Clients',
                    icon: {
                        element: 'img',
                        attributes: {
                            src: '/dist/user.png',
                        },
                    },
             },
    },
    methods: {
    },
}
</script>

<style scoped>
.v-sidebar-menu { /* this class works */
    width: 220px;
    padding-top: 28px;
    z-index: 20;
    background: linear-gradient(#6078EA 0%, #22D9DB 100%);
}

.sidebar .v-sidebar-menu .vsm--item { /* this class doesn't work */
  height: 33px;
  color: #555D6C;
  font-family: Roboto;
  font-size: 28px;
  line-height: 33px;
  background-color: #FFF;
}

</style>
```

Any suggestions?

**Comment by yaminncco** [comment]
doesn't work because of `scoped` styles doesnt apply to child components

**Comment by gtzures** [comment]
Thanks! Did the trick.
