### ISSUE TITLE
Unknown custom element: <separator>

### ISSUE THREAD

**Issue by bustarice** [yaminncco/vue-sidebar-menu#106]
I was following the suggestions here:
[https://github.com/yaminncco/vue-sidebar-menu/issues/102](https://github.com/yaminncco/vue-sidebar-menu/issues/102)

However, I am met with `Unknown custom element: <separator>`

Am I missing something here?

**Comment by yaminncco** [comment]
can you share some code

**Comment by bustarice** [comment]
sidebar.vue

```
<template>
    <div id="sidebar-container">
		<sidebar-menu
			:menu="menu"
			widthCollapsed="0px"
			width="100%"
			hideToggle
			showOneChild
			theme="white-theme"
		>
		</sidebar-menu>
    </div>
</template>
<script>
    import { SidebarMenu } from 'vue-sidebar-menu'
    import 'vue-sidebar-menu/dist/vue-sidebar-menu.css'
    
    const separator = {
        template: `<hr style="border-color: rgba(0, 0, 0, 0.1); margin: 20px;">`
    }
    
    export default {
        components: {
            SidebarMenu,
        },

        data() {
            return {
                menu: [],
            }
        },

        methods: {
            getCategories() {
                let url = 'categories/getcategoriessidebar'
                axios.get(url, {})
                .then((res) => {
                    this.menu = res.data.categories
                    let hr = {
                        component: separator
                    }
                    this.menu.push(hr)
                }, () => {
                    this.has_error = true
                })
            }
        },

        mounted() {
            this.getCategories()
        }
    }
</script>
```

api json data

`{"categories":[{"href":"\/category\/sports\/soccer","title":"Soccer","hiddenOnCollapse":true}]},{"component":"separator"}]}`

I did an extra step for testing and it seems if I add the separator inside the component it works fine and shows but when I add the separator component as part of the data returned by the api I end up with the aforementioned error on top.

Here is how the menu data looks after I pushed the separator inside component:

`{"categories":[{"href":"\/category\/sports\/soccer","title":"Soccer","hiddenOnCollapse":true}]},{"component":"separator"}, {"component": {"template":"<hr style=\"border-color: rgba(0, 0, 0, 0.1); margin: 20px;\">"}}]`

So as you can see it works when I do it this way.

**Comment by yaminncco** [comment]
because in your data api, component value is a string `"separator"` which is not a registered component name or a component options object.
so either use your solution or register the component globally:
```
Vue.component('separator', {
  template: `<hr style="border-color: rgba(0, 0, 0, 0.1); margin: 20px;">`
})
```

**Comment by bustarice** [comment]
> Vue.component('separator', {
>   template: `<hr style="border-color: rgba(0, 0, 0, 0.1); margin: 20px;">`
> })

Great might just end up doing that. Thanks.
