### ISSUE TITLE
Mark item(s) as active

### ISSUE THREAD

**Issue by grebenyukov** [yaminncco/vue-sidebar-menu#108]
Hi! Thank you for great component! Is it possible to mark one or more items as "active" in menu array? With color or font highlighting. Something like 
{
  href: '/',
  title: 'Dashboard',
  icon: 'fa fa-user',
  active: true
}, ...
It is not always a last clicked item or item with "href == current browser url".
Why more then one - for example, an item on 3rd level (current page), it's parent on 2nd, and it's parent on 1st.
Best regards, Eduard

**Comment by yaminncco** [comment]
for your example this how it's already works, parent will be active when child item is active,
but if only you want to apply active style to a specific item then you can add class:

```
{
  href: '/',
  title: 'Dashboard',
  icon: 'fa fa-user',
  class: 'vsm--link_active'
}
```

**Comment by grebenyukov** [comment]
It's so simple, cool! Thank you!
