### ISSUE TITLE
How to keep menu item active when route is not an exact match

### ISSUE THREAD

**Issue by stefanknegt** [yaminncco/vue-sidebar-menu#109]
I would like to keep a certain item in the menu active when the route changes.

For example route is /settings/users and if this becomes /settings/preferences the menu item should remain active, since we are still on /settings.

What is the best way to achieve this? I saw you added the exactPath property here: https://github.com/yaminncco/vue-sidebar-menu/issues/72, but I am not sure how to use this.

**Comment by yaminncco** [comment]
exactPath is to match path only without hash and query, use alias
