### ISSUE TITLE
Cannot find the place to change the theme.

### ISSUE THREAD

**Issue by GuCatatau** [yaminncco/vue-sidebar-menu#111]
Hi, can you help me with this one. I'm trying to find were can I change the theme of the side bar.

thanks in advance.

**Comment by yaminncco** [comment]
use `theme` prop:

`<sidebar-menu theme="white-theme" />`

**Comment by GuCatatau** [comment]
Hi again yaminnccco, is there any way to put the toggle to hide the sidenav on the header ?

thanks again.

**Comment by yaminncco** [comment]
check this https://github.com/yaminncco/vue-sidebar-menu/issues/100

**Comment by GuCatatau** [comment]
Hi @yaminncco. I'm just using the same issue to not overflow with questions.

I'm not getting to make the child change the page on my project. to make them load another .vue file.

thanks !
