### ISSUE TITLE
DisableHover does not work for click

### ISSUE THREAD

**Issue by stefanknegt** [yaminncco/vue-sidebar-menu#112]
I would like to disable the menu item expanding (when collapsed) when hovering and used disableHover, which worked fine. However, when you click you still get the expanding effect (see attached screenshot). How can I also disable this?
![Screenshot 2020-01-14 at 10 57 21](https://user-images.githubusercontent.com/17021755/72334092-178c2200-36bd-11ea-9885-f4edcedcaa24.png)

**Comment by yaminncco** [comment]
hide it with css 
```
.v-sidebar-menu .vsm--mobile-item {
  display: none;
}
```
