### ISSUE TITLE
Sizing vue-font-awesome icons in sidebar

### ISSUE THREAD

**Issue by stefanknegt** [yaminncco/vue-sidebar-menu#113]
I saw there are more issues on this, but I could not find the answer here. I am using vue-font-awesome icons like this: 

`icon:  { element: 'font-awesome-icon', attributes: {icon:'home'}}`

However, the icons are much larger than the previous ones and I am unable to make the icon itself smaller without changing the size of the square around the icon. How can this be achieved? Thanks a lot!

**Comment by stefanknegt** [comment]
Sorry, I have managed to fix it using the following css: `  .svg-inline--fa {
      padding: 5px !important;
  }`

**Comment by mikecbone** [comment]
Note for others, this made my toggle icon super small so you'll need to define no padding for the toggle icon itself (as this is more specific it will override the general padding given above). 

Also, I don't think `!important` is needed for either. 

In total I have:

```
// Padding for the menu icons
.svg-inline--fa {
  padding: 5px;
}

// More specificity for the no padding toggle icon
.fa-arrows-alt-h {
  padding: 0px;
}
```

And a reminder on how to add the toggle icon using vue-font-awesome as you need to use slots unlike the rest of the menu icons:
```
<sidebar-menu :menu="menu">
      <font-awesome-icon slot="toggle-icon" icon="arrows-alt-h"></font-awesome-icon>
</sidebar-menu>
```

**Comment by amacado** [comment]
I developed the following `scss` snippet to fix the icon sizes without the need to specify the toggle-icons by name (like @mikecbone did). This also works for multi-level structures including icons.

```scss
.vsm--item {
  > a.vsm--link_level-1 {
    >.svg-inline--fa {
      padding: 5px !important;
    }
  }
}
```
