### ISSUE TITLE
Incorrect check for aliases

### ISSUE THREAD

**Issue by kiril-malyhin** [yaminncco/vue-sidebar-menu#115]
Hi,

I've tried to configure aliases and got next problem.
Configuration looks next: 
  [{ title: 'Articles', href: '/stockarticles', alias: [ /^\/stockarticles\/((?:[^\/]+?))(?:\/(?=$))?$/i ], exactPath: true }, ...]
My route looks next: 
/stockarticles/OWt5zlB?tab=information

So, in router I don't specify any query parameters.I looked into your code and found one issue. 
When alias logic is used, you check for matching exact route. Why you don't check for matchRoute function? Of course, if I will check for fullPath they will be not equal
![image](https://user-images.githubusercontent.com/11473999/72435940-57800180-37b0-11ea-8eee-43a5f5c2d7c3.png)

**Comment by yaminncco** [comment]
your using old version, regex is supported in v4.4.0

**Comment by kiril-malyhin** [comment]
hi @yaminncco , I've used old version, you are right. But, issue is still there. 
In code you calculate current from current route from fullPath. Full path has all values, including query and hashes. If I have a configuration for exact path< i would guess, that you retrieve current as this.$route.path
![image](https://user-images.githubusercontent.com/11473999/72501400-b2b10300-3847-11ea-8d10-bfc3298c5b45.png)

**Comment by kiril-malyhin** [comment]
hey @yaminncco , thx!

**Comment by BaxAndrei** [comment]
> your using old version, regex is supported in v4.4.0

Is this regex function also available in the latest version (@next)?

**Comment by yaminncco** [comment]
@BaxAndrei No, alias can be configured vue-router routes

**Comment by BaxAndrei** [comment]
I have a route like this: `{ ... path: '/angebots/edit/:id(\\d+)', ... }` and I don't know how to set it to active when it's on this page.

**Comment by yaminncco** [comment]
If you want `/angebots/edit/` to be active then set route like this:

```
import { h } from 'vue'
import { RouterView } from 'vue-router'
...
{
  path: '/angebots/edit/',
  component: { render: () => h(RouterView) },
  children: [
    {
      path: ':id(\\d+)',
      component: EditComponent
    }
  ]
}
```
