### ISSUE TITLE
Collapse after click is not working on Touch

### ISSUE THREAD

**Issue by ciacco85** [yaminncco/vue-sidebar-menu#117]
Hi, thank you for your work: finally a really good sidebar plugin for Vue.

**On collpsed state**, when I hover on a Menu item with child, only the child of that menu will open and, when i move the mouse, that menu will close: I think it's due to some hover functionality that is working fine.

On mobile, since there's no concept of hover, I've to click outside the menu to close that child.

I can't even use collapse state, since I can't collapse only the child menu and, as I stated, the whole menu is already collapsed.

This happen in you very same demo page, obviously on DropDown page where there're child

**Comment by yaminncco** [comment]
not sure if i miss understood because its working fine for me, tested in android and chrome devtools

**Comment by JorgenSolli** [comment]
I solved this by setting a ref on sidebar-menu with an item-click event
`<sidebar-menu ref="menu" @item-click="onItemClick">`

And then on the click-event we can set the child-menu to null like so

```
onItemClick(event, item) {
    this.$refs.menu.mobileItem = null
},
```

**Comment by ciacco85** [comment]
works like a charm
