### ISSUE TITLE
Open/close/collapse items programmatically

### ISSUE THREAD

**Issue by rrrmity** [yaminncco/vue-sidebar-menu#118]
Hi there! 
Thanks for this great piece of software.
I'm trying to open/close (change the collapse state for) a specific child of a menu programmatically. 
I couldn't find a way to achieve this, but maybe I'm looking for the wrong things. 
Could anyone give me a hint in the right direction?

More details on what I try:
If an item in submenu A is clicked, submenu A should be closed/collapsed and submenu B should be opened/uncollapsed.

Thanks in advance ...

Best regards
Michael

**Comment by D4RKAR117** [comment]
Hello, @rrrmity I think you can acomplish this looking at this css classes and ther interaction with child items in the list 

```css 
.v-sidebar-menu .vsm--item {}
.v-sidebar-menu .vsm--item.vsm--item_open {}
.v-sidebar-menu .vsm--link {}
.v-sidebar-menu .vsm--link.vsm--link_active {}
.v-sidebar-menu .vsm--link.vsm--link_exact-active {}
```

Im not sure wich one is the specific class but i think is the easier aproach to your problem :D .

Let me know if this helps.

**Comment by rrrmity** [comment]
@D4RKAR117 Thank you very much. This seems a pretty idea, but I'm not sure, that this works. 

As far as I can see and try right now, uncollapsing an item (AKA showing it's children) is changing the markup itself by adding the submenu markup dynamically. So I can make the parent menu make look uncollapsed, but the submenu markup isn't there. 

Or is there something else that needs to be done beside adding the class to the item?

**Comment by D4RKAR117** [comment]
@rrrmity Maybe you want to look at [this](https://github.com/yaminncco/vue-sidebar-menu/blob/master/src/components/SidebarMenuItem.vue), this is how the menu items check and change with their childs. I dont know how this work pretty well, so until @yaminncco  response i cant think in anything more :/

**Comment by yaminncco** [comment]
sorry but there no option to open/close a specific child, adding class is not gonna work
