### ISSUE TITLE
[Feature Request] Add Vetur Tag Intellisense Compat 

### ISSUE THREAD

**Issue by D4RKAR117** [yaminncco/vue-sidebar-menu#119]
To improve the experience using the package, it would be good to carry out an integration at a lower level, with one of the most used development tools like vetur or vscode.

As an example of this integration, another library such as Bootstrap Vue, as shown **[here](https://bootstrap-vue.js.org/docs#tooling-support)**, and as an example of creation, example **[here](https://github.com/bootstrap-vue/bootstrap-vue-helper-json)**.

This will allow other integrations to be completed, such as the typescript definitions. Regardless of whether it is used with or without typescript, or as local components or as a Vue plugin

**Comment by yaminncco** [comment]
i don't think its necessary since this lib is too small compared to BootstrapVue
