### ISSUE TITLE
How do we use router preprocessor with vue sidebar-menu?

### ISSUE THREAD

**Issue by alperkal** [yaminncco/vue-sidebar-menu#121]
```
      beforeEnter(to, from, next) {
        console.log('before enter');
      },
```

When I enable beforeEnter, I loose complete navigation and components stop loading. Have any idea why this would happen? (Using latest version )

Thanks

**Comment by yaminncco** [comment]
you didn't call `next` function to resolve the hook

**Comment by alperkal** [comment]
oh
