### ISSUE TITLE
Collapse with event @item-click not working properly

### ISSUE THREAD

**Issue by dlenskyi** [yaminncco/vue-sidebar-menu#127]
<img width="431" alt="Снимок экрана 2020-04-07 в 19 45 58" src="https://user-images.githubusercontent.com/44784628/78696858-abf6d100-7908-11ea-9c63-c3eb1c279d4b.png">
<img width="431" alt="Снимок экрана 2020-04-07 в 19 46 03" src="https://user-images.githubusercontent.com/44784628/78697065-ebbdb880-7908-11ea-9a3a-e0261ac44e23.png">

When clicking on items, I need to collapse sidebar, at the first click it really collapses, but rest attempts don't collapse the sidebar and I get error in console, above

**Comment by yaminncco** [comment]
don't mutate the props directly, set `collapsed` in the data

```
<template>
  <sidebar-menu :collapsed="collapsed"></sidebar-menu>
</template>

data() {
  return {
    collapsed: true
  }
}
```

then change it

```
onItemClick (event, item) {
  this.collapsed = true
}
```

**Comment by dlenskyi** [comment]
Thanks!
