### ISSUE TITLE
[SOLVED] Icons missing

### ISSUE THREAD

**Issue by dschiller** [yaminncco/vue-sidebar-menu#130]
After Installing `npm i vue-sidebar-menu --save` no Icons visible. Tried to install Font Awesome but hat doesn't fix it.

![image](https://user-images.githubusercontent.com/3144986/79058405-f6ac7c00-7c6d-11ea-8491-b316cfef519a.png)

**Comment by yaminncco** [comment]
how did you import font-awesome?
can you show some code

**Comment by dschiller** [comment]
I used `npm install font-awesome` and `@import "node_modules/font-awesome/scss/font-awesome.scss";`

**Comment by yaminncco** [comment]
your installing font-awesome v4 if that's what you want, then you need to use icons from [here](https://fontawesome.com/v4.7.0/icons/)
for the arrows and toggle override with css
```
.v-sidebar-menu .vsm--arrow:after {
  content: '\f105';
  font-family: 'FontAwesome';
}
.v-sidebar-menu .vsm--toggle-btn:after {
  content: '\f07e';
  font-family: 'FontAwesome';
}
```
or use slots 
```
<sidebar-menu>
  <i class="fa fa-chevron-right" slot="dropdown-icon"></i>
  <i class="fa fa-arrows-h" slot="toggle-icon"></i>
</sidebar-menu>
```

**Comment by jeff-hykin** [comment]
This was easier and worked for me

`npm install font-awesome`
```
<style>
$fa-font-path: "~font-awesome/fonts/";
@import "~font-awesome/scss/font-awesome.scss";
</style>
```
