### ISSUE TITLE
titles not updated when changing language

### ISSUE THREAD

**Issue by tmzwinkels** [yaminncco/vue-sidebar-menu#131]
When I change language (button on screen) , my complete website is updated with the new language, except my sidebar menu. 

My implementation 
`<sidebar-menu showOneChild :menu="menu"/>` 

I moved the menu return to computed instead of data 

`
    computed: {
            menu () {
                return [
                    {
                        header: true,
                        title: this.$t('menu'),
                    },
                    {
                        title: this.$t('dashboard'),
                        icon: 'pe-7s-home',
                        href: '/dashboard',
                    }
                ]
            }
        }
`

The sidebar is updated when I completely refresh the page.

I'm using sidebar menu version 3.12.2
Vue is on version 2.6.11

**Comment by yaminncco** [comment]
computed menu works fine, I don't know what your issue is
example: https://codesandbox.io/s/modern-sound-8ypj9
