### ISSUE TITLE
Collapsed item on start

### ISSUE THREAD

**Issue by HighCoData** [yaminncco/vue-sidebar-menu#132]
Is there an option to have the items (not the menu) collapsed on start? 
Right now as soon as I click on one item and I refresh the page, that item stays open. 
Is there a prop that prevents this? 

Thanks!

**Comment by yaminncco** [comment]
There's no option but you can still close, here my solution:

```
<sidebar-menu ref="sidebar" />
```
```
mounted() {
  this.$nextTick(() => {
    for (let item of this.$refs.sidebar.$children) {
      item.itemShow = false
    }
  })
}
```

using showOneChild prop:

```
mounted() {
  this.$nextTick(() => {
    this.$refs.sidebar.activeShow = null
  })
}
```

**Comment by HighCoData** [comment]
@yaminncco 
thanks for the answer but unfortunately it doesn't work
It's not doing anything and I'm not getting any errors.
I have even tried it like this:
```
const children = this.$refs.sidebar.$children
            Object.keys(children).forEach(function(key) {
                console.log(key, children[key])
            })
```
But it's still not giving me anything

**Comment by yaminncco** [comment]
you need to run it after the menu fully loaded
