### ISSUE TITLE
Padding left changes quicker than sidebar collapse causing overlap

### ISSUE THREAD

**Issue by sdwru** [yaminncco/vue-sidebar-menu#133]
You can see this on the [demo](https://yaminncco.github.io/vue-sidebar-menu/#/) when you collapse the menu. I can also reproduce this on my app.  

When you collapse the menu the onToggleCollapse method changes the padding to
```
#demo.collapsed {
    padding-left: 50px;
}
``` 
This takes effect immediately with no transition time.  However, the sidebar collapse occurs as a transition over time by default.  The result is a brief overlap which is not very refined looking.  

The simple fix is to add transition to `#demo` css and match it to this components default transition setting.
```
#demo {
  padding-left: 350px;
  transition: 0.3s ease;
}
```
However, I would think that transition time should be tied directly to this components transition time by default so that it happens automatically and perfectly in sync.  At the very least, the demo should have the transition added to the css to make the demo look more refined.

**Comment by yaminncco** [comment]
issue is related to the demo not the component, fixed thanks
