### ISSUE TITLE
[Vue warn]: Error in render function: "TypeError: t._g is not a function"

### ISSUE THREAD

**Issue by grahamroy** [yaminncco/vue-sidebar-menu#135]
I am using a Vue front end to a C# back end with typescript. I have added vue-sidebar-menu and configured my project as follows:

**navmenu.vue.html**

```
<template>
    <div>
        <sidebar-menu :menu="menu" @toggle-collapse="onToggleCollapse" @item-click="onItemClick" /> 
        
    </div>
  </template>

  <script src="./navmenu.ts"></script>
```

**navmenu.ts**
```

import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import { SidebarMenu } from 'vue-sidebar-menu'

@Component({
    components: {
        SidebarMenu
    }
})

export default class MenuComponent extends Vue{
    data() {
        return {
            menu : [
  
                {
                    header: true,
                    title: 'Main Navigation',
                    hiddenOnCollapse: true
                },
                {
                    href: '/',
                    title: 'Dashboard',
                    icon: 'fa fa-user'
                }
            ]
        }
    }
        onToggleCollapse(collapsed: boolean) {
            console.log(collapsed);
        };
        onItemClick(event: any, item: any) {
            console.log(item);
        };
    
}
```
this returns the error:

[Vue warn]: Error in render function: "TypeError: t._g is not a function"

found in

---> <SidebarMenuItem> at SidebarMenuItem.vue
       <SidebarMenu> at SidebarMenu.vue
         <MenuComponent> at D:\Projects\Vue2\ClientApp\components\navmenu\navmenu.vue.html
           <AppComponent> at D:\Projects\Vue2\ClientApp\components\app\app.vue.html
             <Root>

If I remove all of the menu entries except for the header then it loads fine, I get the 'Main Navigation' as the header, but obviously nothing else.

How can I add additional menu items without causing this problem?

![image](https://user-images.githubusercontent.com/344499/82496675-06c54000-9ae5-11ea-90e7-5e1edcd0287b.png)

Many thanks

**Comment by yaminncco** [comment]
can you reproduce the issue?

**Comment by grahamroy** [comment]
sure. do you want me to make a github repo?

**Comment by yaminncco** [comment]
i think you need to update vue

**Comment by grahamroy** [comment]
I am using version 2.6.11. Here's my package.json

{
  "name": "Vue2",
  "private": true,
  "version": "0.0.0",
  "devDependencies": {
    "@types/webpack-env": "^1.15.2",
    "aspnet-webpack": "^2.0.3",
    "awesome-typescript-loader": "^3.5.0",
    "bootstrap": "^3.4.1",
    "css-loader": "^0.25.0",
    "event-source-polyfill": "^0.0.7",
    "extract-text-webpack-plugin": "^2.0.0-rc.3",
    "file-loader": "^0.9.0",
    "isomorphic-fetch": "^2.2.1",
    "jquery": "^3.5.1",
    "style-loader": "^0.13.1",
    "typescript": "~3.3.0",
    "url-loader": "^0.5.7",
    "vue": "^2.6.11",
    "vue-loader": "^11.1.4",
    "vue-property-decorator": "^5.3.0",
    "vue-router": "^2.8.1",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^2.7.0",
    "webpack-hot-middleware": "^2.25.0"
  },
  "dependencies": {
    "vuex": "^3.4.0"
  }
}

**Comment by yaminncco** [comment]
hmm, I am able to reproduce the issue by using old version of vue, make sure you don't have a mismatch version, otherwise I need a repo
