### ISSUE TITLE
How to use class .vsm--link_exact-active

### ISSUE THREAD

**Issue by juanfgaliana** [yaminncco/vue-sidebar-menu#136]
Hello, I would like to know how to apply the class .vsm - link_exact-active, I have in the menu, in several sections, repeated links by role topic, and when I activate one of those repeated links, the active state is enabled in the two options, I would like to know how to activate it only in the link that I access.

Thank you

**Comment by yaminncco** [comment]
i don't fully understand because the class should apply when href match exactly current route,
need more details
