### ISSUE TITLE
Not possible to add a link to the header item.

### ISSUE THREAD

**Issue by klattimer** [yaminncco/vue-sidebar-menu#141]
Often you want a linkable logo which takes the user to the homepage or dashboard but this is not possible with vsm.

**Comment by yaminncco** [comment]
you can achieve this, by using the component property you can make your own custom item
PR is not needed

**Comment by klattimer** [comment]
I can't see anywhere in the documentation that this is possible. Looking through the code it also didn't seem possible, could you provide an example?

**Comment by yaminncco** [comment]
in the same way you make a divider you can make a linkable header, you can even pass props

```
const linkableHeader = {
  template: `<a class="vsm--header" :href="href">{{ title }}</a>`,
  props: ['title', 'href']
}

// menu
{
  component: linkableHeader,
  props: {
    title: 'header',
    href: '/'
  }
}
```
