### ISSUE TITLE
use SVG as icon

### ISSUE THREAD

**Issue by al-burger** [yaminncco/vue-sidebar-menu#143]
Hi, i'd like to use my SVG as icon on the sidebar so i can change their color in hover for exemple. Actualy i have succeed to use them but they are used as <img>, so i cant change their color with fill in my css.

My code looks like this : 

<template>
  <sidebar-menu :menu="menu" collapsed="true" width="200px" />
</template>

<script>
import cardSVG from '../svg/cards.svg'
import deckSVG from '../svg/deck.svg'
export default {
  data() {
    return {
      menu: [
        {
          header: false,
          hiddenOnCollapse: true,
          hidden:true
        },
        {
          href: "/",
          title: "Liste de cartes",
          icon: {
           //adjust element
            element: 'img',
            attributes: { src: cardSVG },
          },
        },
        {
          href: "/charts",
          title: "Galeries de decks",
          icon: {
           //adjust element
            element: 'img',
            attributes: { src: deckSVG },
          },
        }
      ]
    };
  }
};
</script>

Thank you :)

**Comment by yaminncco** [comment]
my suggestion is to convert the icons into single-file components or use [vue-svg-loader](https://vue-svg-loader.js.org/)
