### ISSUE TITLE
@item-clicked does not work if menu item is of type 'component' 

### ISSUE THREAD

**Issue by kunalmkamble** [yaminncco/vue-sidebar-menu#145]
Prerequisite: 
One of the item from the menu should be a **component**

Why this is needed?
itme-clicked is not fired when item is of type component. 

You can pass props to a menu item of using **props** but there is no way to supply **event**. Is it possible to have  events are supported for the component type items?

**Comment by yaminncco** [comment]
well you can do `this.$parent.$parent.$emit('my-event')` from the component (first level only)
or a better solution is to use bus or state management
