### ISSUE TITLE
support for Inertia JS inertia-link

### ISSUE THREAD

**Issue by suleodu** [yaminncco/vue-sidebar-menu#146]
How can i use vue-sidebar-menu for  inertia-link example https://inertiajs.com/routing

**Comment by yaminncco** [comment]
sorry but only vue-router is supported, I might add an option for 3rd-party routers

**Comment by suleodu** [comment]
Okay Thanks. That will be a great one

**Comment by suleodu** [comment]
> sorry but only vue-router is supported, I might add an option for 3rd-party routers
Like how soon can you add that?

**Comment by yaminncco** [comment]
I don't know when, if all what you need is to navigate than what you can do is to replace the `href` property with any name ex: 'to', then using @item-click event you can make a route request so with inertia: `this.$inertia.visit(item.to)`
its a temporary solution so some features might not work

**Comment by suleodu** [comment]
Thanks that works fine just that my current linknis not set active

**Comment by DanishRasali** [comment]
Thank you! Just what I needed!

**Comment by yaminncco** [comment]
supported in v5 https://github.com/yaminncco/vue-sidebar-menu#customize-link
