### ISSUE TITLE
The main content part is not sliding to right

### ISSUE THREAD

**Issue by trenzasoft** [yaminncco/vue-sidebar-menu#147]
I am not sure if this is an issue or not but I need help here. Thank you for this awesome thing.
I am trying to implement this in my laravel project which is using bootstrap-vue.org 

The menu is appeared on left site but when the menu expand the main content part is moving to right. Here is my laravel layout blade file.
[app.blade.txt](https://github.com/yaminncco/vue-sidebar-menu/files/4831894/app.blade.txt)

**Comment by trenzasoft** [comment]
> 
> 
> I am not sure if this is an issue or not but I need help here. Thank you for this awesome thing.
> 
> I am trying to implement this in my laravel project which is using bootstrap-vue.org
> 
> The menu is appeared on left site but when the menu expand the main content part is moving to right. Here is my laravel layout blade file.
> @yield('content')
> <script src="{{ asset('public/js/app.js') }}" defer></script>

**Comment by yaminncco** [comment]
you need to add padding-left (or margin-left) to the main depending on the sidebar collapse
check [demo](https://github.com/yaminncco/vue-sidebar-menu/blob/master/demo/App.vue#L4) can help

**Comment by trenzasoft** [comment]
> 
> 
> you need to add padding-left (or margin-left) to the main depending on the sidebar collapse
> check [demo](https://github.com/yaminncco/vue-sidebar-menu/blob/master/demo/App.vue#L4) can help

Yaminncco - thank you for the reply. It will be a big help if you could check the attached file that I have added with the issue and let me know what I am doing wrong here?

**Comment by yaminncco** [comment]
what trouble you're facing? you can make a component and put the sidebar there and pass the content via slot, so something like this:

```
// AppMain.vue
<template>
    <div>
        <sidebar-menu :collapsed="collapsed" @toggle-collapse="onToggleCollapse" />
        <main class="main" :class="{'collapsed' : collapsed}">
            <slot></slot>
        </main>
    </div>
</template>

<script>
    export default {
        data() {
            return {
                collapsed: false,
            }
        },
        methods: {
            onToggleCollapse (collapsed) {
                this.collapsed = collapsed
            },
        }
    }
</script>

<style scoped>
.main {
    padding-left: 350px;
}
.main.collapsed {
    padding-left: 50px;
}
</style>
```

then in app.blade:
```
<div id="app">
    <app-main>
        @yield('content')
    </app-main>
</div>
```

hope this helps

**Comment by trenzasoft** [comment]
> 
> 
> what trouble you're facing? you can make a component and put the sidebar there and pass the content via slot, so something like this:
> 
> ```
> // AppMain.vue
> <template>
>     <div>
>         <sidebar-menu :collapsed="collapsed" @toggle-collapse="onToggleCollapse" />
>         <main class="main" :class="{'collapsed' : collapsed}">
>             <slot></slot>
>         </main>
>     </div>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {
>                 collapsed: false,
>             }
>         },
>         methods: {
>             onToggleCollapse (collapsed) {
>                 this.collapsed = collapsed
>             },
>         }
>     }
> </script>
> 
> <style scoped>
> .main {
>     padding-left: 350px;
> }
> .main.collapsed {
>     padding-left: 50px;
> }
> </style>
> ```
> 
> then in app.blade:
> 
> ```
> <div id="app">
>     <app-main>
>         @yield('content')
>     </app-main>
> </div>
> ```
> 
> hope this helps

It works now. How awesome this is! Just one thing - the icons are not loading though I have installed the fontawsome form https://github.com/FortAwesome/vue-fontawesome

**Comment by trenzasoft** [comment]
Fix the icon issue. Thanks again.

**Comment by yaminncco** [comment]
you shouldn't ask help without doing prior research or giving any details, check this https://github.com/yaminncco/vue-sidebar-menu/issues/96#issuecomment-559464437
