### ISSUE TITLE
can't change sidebar icon background color

### ISSUE THREAD

**Issue by MrCSimon** [yaminncco/vue-sidebar-menu#148]
when applying this style, 

.v-sidebar-menu .vsm--link_level-1.vsm--icon  { background-color: #32373d !important; }

in my vue component, the icon background does not change, but it works in chrome debugger when changing the background.

please advise

**Comment by Xavoski** [comment]
I was not able to change many of css.
The default css from my app.js
(`import "vue-sidebar-menu/dist/vue-sidebar-menu.css";`) always used to overwrite my customization.

The only way i found to fix this was remove the css importation and copy all css files from here and create
them in my application and import 
`@import "./sidebar/vue-sidebar-menu.scss";` 
in my app.scss.

I accept any suggestion to reverse this.

**Comment by MrCSimon** [comment]
@Xavoski thanks for the tip. that worked! not ideal, but it'll do.

**Comment by yaminncco** [comment]
your selecting wrong target it's `.v-sidebar-menu .vsm--link_level-1 .vsm--icon`
@Xavoski make sure you import override after the sidebar style or override with a more specific class

**Comment by Xavoski** [comment]
Hello,
Thanks @yaminncco for your work and attention.
And @MrCSimon , i guess i got it. Do not import the css in your _app.js_ file.

I moved it to the _app.scss_ file like this:
`
// Sidebar
@import "vue-sidebar-menu/dist/vue-sidebar-menu"; // Original css.
@import "./sidebar/vue-sidebar-menu"; // My custom sidebar menu css.
`
