### ISSUE TITLE
*improvement* menu on mobile (iOS)

### ISSUE THREAD

**Issue by puschie286** [yaminncco/vue-sidebar-menu#153]
hi,
had struggle to get the menu working on mobile when page content is longer than the view
( only tested on ios devices )
solution was to use the available instead of constant 100vh which is does not respect mobile toolbar hide/show
`.v-sidebar-menu {
    height: -webkit-fill-available;
  }`

` .v-sidebar-menu .vsm--scroll-wrapper {
    height: calc( -webkit-fill-available - 50px )
  }`

would be nice if can integrate this.
i guess it should be tested how it behave when the menu content is longer than the screen height but for it works for testing purpose
*solution based on [this information](https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/)*

**Comment by yaminncco** [comment]
new version fix this can you confirm

**Comment by puschie286** [comment]
Yes works great on mobile now
Awesome work 👍
