### ISSUE TITLE
Icons not appearing

### ISSUE THREAD

**Issue by ElevenTech** [yaminncco/vue-sidebar-menu#154]
Icons are not appearing for me.
I have installed the font awesome icons via npm and am able to view icons placed within the template i.e.
`<fa-icon :icon="['fas', 'user-secret']"/>,`

but I can't view icons set in the export default data function i.e.
```
{
href: '/about',
title: 'About',
icon: 'fa-info-circle'
},
```

Is there anything specifically needed to get those to appear?

**Comment by yaminncco** [comment]
custom icon:
```
  icon: {
    element: 'fa-icon',
    attributes: {
      icon: ['fas', 'user-secret']
    }
  }
```
