### ISSUE TITLE
Adding a subtitle above the navigation title

### ISSUE THREAD

**Issue by coenhallie** [yaminncco/vue-sidebar-menu#157]
Hello,

I would like to add a small text above a specific navigation item title, however I am not sure how to achieve that. Can you please guide me how that would be possible?

Many thanks,

Coen
![nav-subtext](https://user-images.githubusercontent.com/12600211/93387004-d7db9280-f868-11ea-987c-5154d0f4a53a.png)

**Comment by yaminncco** [comment]
not possible, but I think maybe you should make a header item instead

**Comment by coenhallie** [comment]
> not possible, but I think maybe you should make a header item instead

Ah yes that worked perfectly, thanks for the suggestion!
