### ISSUE TITLE
Vue 3.0 version

### ISSUE THREAD

**Issue by Gelbpunkt** [yaminncco/vue-sidebar-menu#158]
Hi there - is it possible to add support for Vue 3.0.0? This component is amazing but it is more or less broken in the new version

**Comment by TCLNA** [comment]
How much broken ?

**Comment by yaminncco** [comment]
I haven't check Vue 3 yet so there's no plans right now

**Comment by FarhanShares** [comment]
Is it supported now?

**Comment by TCLNA** [comment]
@FarhanShares https://semver.org/

**Comment by yaminncco** [comment]
I am working on it I just don't have a date for that

**Comment by FarhanShares** [comment]
Okay, that would be great. Thanks for the awesome vue-sidebar-menu.

**Comment by mrscaper** [comment]
Thank you for working on a vue 3 version @yaminncco.  Do you have any status updates to share with us?

**Comment by yaminncco** [comment]
you can track changes in this branch [next]( https://github.com/yaminncco/vue-sidebar-menu/tree/next)

**Comment by mrscaper** [comment]
Looks like you're making great progress, any chance of a beta build coming to npm?

**Comment by yaminncco** [comment]
released alpha version you can guys test it `npm install vue-sidebar-menu@alpha`

**Comment by mariusa** [comment]
Confirming 5.0.0-alpha.9 works fine on vue 3. What's remaining to push this as a stable 5.x release?

**Comment by yaminncco** [comment]
v5 is released now

**Comment by mariusa** [comment]
It's not published to npm yet? https://www.npmjs.com/package/vue-sidebar-menu
