### ISSUE TITLE
Hide arrow when child is an empty array

### ISSUE THREAD

**Issue by coenhallie** [yaminncco/vue-sidebar-menu#159]
Hello,

My backend developer is not able to check if a navigation item has children or not. So he will return all navigation items with either an empty child array or one that is filled. Now I need to hide the arrow on a navigation item with an empty child array. Is that possible? I am using the 'dropdown-icon' slot.

Many thanks,

Coen

**Comment by yaminncco** [comment]
fixed in v4.7.2
