### ISSUE TITLE
Color customization sample

### ISSUE THREAD

**Issue by pablodegrande** [yaminncco/vue-sidebar-menu#16]
It would be great if you could provide a sample for customizing colores to a google-like palette (white, like https://codepen.io/zavoloklom/details/dIgco). A boolean flag for 'WhiteTheme' would also be awsome, as so many sites are white nowaways. I updated the component and lost previous customizations due to style changes.

It would also be great if you add ! default to each var.scss variable, so that anyone can define them first and override those values.

**Comment by yaminncco** [comment]
In the next update I will add the styles files to the package so you can use the var.scss for color customization, as for now you can customize only with css.

**Comment by discontinuos** [comment]
Great! I think it would be nice if you could provide then a working sample for white style, as changing to white requires many many color changes (background, foreground, selection, hover, link....)....

**Comment by yaminncco** [comment]
in v3.0.0 you can override sass var, and you can also change to white-theme.

**Comment by pablodegrande** [comment]
Amazing!
