### ISSUE TITLE
Class vsm--link_active is not activated automatically

### ISSUE THREAD

**Issue by AlandEr2612** [yaminncco/vue-sidebar-menu#161]
Hi!, I have a problem with the "active / not active" status of the menu items, when I click on one of the menu items the class "vsm--link_active" that should be applied is not applied, to put you in context, I am using the library with CDN as global component, from this url:

- "https://unpkg.com/vue-sidebar-menu/dist/vue-sidebar-menu.css"
- "https://unpkg.com/vue-sidebar-menu/dist/vue-sidebar-menu.js"

I relied on this code to implement the library: https://codepen.io/muthu32/pen/ydgdEQ

Where it does not work either, but I have not been able to make the "active" class work when I click, I have to do it manually, but it fails, it is only placed the class when I hover on the element, I don't know if it is mandatory to use the router for it to work correctly, here is my implementation:

`<sidebar-menu class="shadow-sm" :menu="menu" :relative="true" :theme="'white-theme'"
        @toggle-collapse="onToggleCollapse" @item-click="onItemClick"></sidebar-menu>
    <div class="geh-menu-item-container" :class="[{'collapsed' : collapsed}]" :is="currentMenuItem"
        :swap-item="swapItem"></div>`

      resolve({
        components: {
          tasks,
          organizationalDesign,
        },
        data() {
          return {
            collapsed: false,
            currentMenuItem: "organizational-design",
            menu: [
              {
                id: 0,
                header: true,
                title: "Bienvenido",
                hiddenOnCollapse: true,
              },
              {
                id: 1,
                title: "Inicio",
                icon: "fas fa-home",
              },
              {
                id: 2,
                title: "Diseño organizacional",
                icon: "fas fa-hospital-alt",
                view: "organizational-design",
              },
              {
                id: 3,
                title: "Tareas",
                icon: "fas fa-tasks",
                view: "tasks",
              },
            ],
          };
        },
        methods: {
          onToggleCollapse(collapsed) {
            this.collapsed = collapsed;
          },
          onItemClick(event, item, node) {
            this.menu.forEach((element) => {
              if (element.id == item.id) {
                element.class = "vsm--link_active";
              } else {
                element.class = "";
              }
            });
            this.swapItem(item.view);
          },
          swapItem(component) {
            this.currentMenuItem = component;
          },
        },
        mounted() {},
        props: ["context"],
        template: html,
      });

Thanks in advance.

**Comment by yaminncco** [comment]
It doesn't work because the class property is not reactive, you need to declare  it first in the data.
see https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties

**Comment by AlandEr2612** [comment]
Ok, let me tell you that it worked for me by placing the class attribute in the menu items, example:

data() {
          return {
            collapsed: false,
            currentMenuItem: null,
            lastIndexSelected: 1,
            menu: [
              {
                id: 0,
                header: true,
                title: "Bienvenido",
                hiddenOnCollapse: true,
                class: "",
              },
              {
                id: 1,
                title: "Inicio",
                icon: "fas fa-home",
                class: "vsm--link_active",
              },
              {
                id: 2,
                title: "Diseño organizacional",
                icon: "fas fa-hospital-alt",
                view: "organizational-design",
                class: "",
              },
              {
                id: 3,
                title: "Tareas",
                icon: "fas fa-tasks",
                view: "tasks",
                class: "",
              },
            ],
          };
        },
        
Thanks!
