### ISSUE TITLE
How the icons are loaded ?

### ISSUE THREAD

**Issue by darkomenx** [yaminncco/vue-sidebar-menu#163]
Can you tell me how (the technical rule) your module load the icon key in your menu array object into the component ?

<img width="305" alt="image" src="https://user-images.githubusercontent.com/16452686/99917991-5135ac80-2d14-11eb-86dd-e0ec54220e2c.png">

Because I already font-awesome installed vue special package and loaded in my renderer process. But I do not have any icons displayed.

What kind of means I can use for replace this value (url, text, ...) :  

`icon: 'fa fa-chart-area',`

Thanks for your work, it seems to be exactly what I need

**Comment by yaminncco** [comment]
if your using font-awesome the icon property need is the class name, if your using vue-fontawesome then check https://github.com/yaminncco/vue-sidebar-menu/issues/96#issuecomment-559464437

**Comment by darkomenx** [comment]
I used this solution : 

```
// menu
{
  href: '/',
  title: 'Homepage',
  // custom icon:
  icon: {
    element: 'font-awesome-icon',
    attributes: {
      // icon props:
      icon: 'user-secret'
    }
  }
}
```

Thank you : ) 
But can you tell me why just the 'user-secret' icon display ? If a try lot of other means to write attributes.icon but nothing appear. Like 'arrow-right' or 'fa arrow-right' etc....

**Comment by yaminncco** [comment]
you need to add the icons to the library first

**Comment by darkomenx** [comment]
I already have this in my renderer.js process file : 

```
import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faUserSecret)
library.add(faFontAwesome)

Vue.component('font-awesome-icon', FontAwesomeIcon)
```

My icon library work perfectly like this : 

<img width="51" alt="image" src="https://user-images.githubusercontent.com/16452686/100451485-cc51e680-30b7-11eb-9f09-b2cb74a6d9e5.png">

with this code : 

`<b-icon-house style="width: 40px; height: 40px; position: relative; right: 10px" variant="info"></b-icon-house>`


Why I can use easily fontawesome with BootstrapVue and with your module it not run ?

Who do you interpret the string 'fa fa-chart-area' for loading and display icon in your module ?

Dealing with this font-awesome page icon, what is the exact name do need for your module loading correctly icon ? (with fa ? without fa ? ) It's ambigous....

**Comment by yaminncco** [comment]
bootstrap uses its own icons and not fontawesome icons, and like I said you need to add the icons that you want to use to the library first, check vue-fontawsome documentation https://github.com/FortAwesome/vue-fontawesome#why-use-the-concept-of-a-library
