### ISSUE TITLE
On hover event

### ISSUE THREAD

**Issue by Rockforge** [yaminncco/vue-sidebar-menu#164]
Hello, would like to know if there is an on hover event for this menu, if not, what would be the possible implementation for this.

**Comment by yaminncco** [comment]
you can listen to `mouseenter` and `mouseleave` event

**Comment by Rockforge** [comment]
Thank you. Used  `mouseover.native` and `mouseleave.native` 

`        <sidebar-menu
            :menu="menu"
            :collapsed="isCollapsed"
            v-on:mouseover.native="mouseover"
            v-on:mouseleave.native="mouseleave"
        ></sidebar-menu>
`
