### ISSUE TITLE
Automatically close popup menu on mobile devices

### ISSUE THREAD

**Issue by cuntis** [yaminncco/vue-sidebar-menu#165]
When the sidebar is collapsed, on desktop shows a popup menu on hover an item, and in mobile device the popup menu shows on tap an item. This works as expected, but in desktop when the user cliks a link that popup closes and the navigation happens and in mobile devices the popup doesn't close, just navigate to the link.

Is there any way to hide the popup on mobile devices when the user clicks on a link?

**Comment by yaminncco** [comment]
It already does what you're expecting to do, how to reproduce the issue?

**Comment by cuntis** [comment]
I think I didn't explain myself. In mobile devices the popup doesn't close when the user clicks the link, but in desktop it does. I want that the popup on mobile devices works like in desktop, I mean, when the user clicks on a link the popup closes. Currently to close it the user must click outside the sidebar, and the user experience is not the best.

**Comment by yaminncco** [comment]
weird because on mobile it does automatically close when click and on desktop it doesn't close because of hover, i need to know how to reproduce the issue can you test the demo page and see how it works

**Comment by carlos00027** [comment]
see you evidence follow link 

https://sanchezacero.com.co/evidences/screen.mp4

**Comment by carlos00027** [comment]
When you click on the submenus from the mobile view, the menu is not hidden, it is still open and you have to click outside the menu so that it closes

i don't speak english

**Comment by yaminncco** [comment]
@carlos00027 clicking on submenus don't hide the popup is intended, just to account for accidental click.
