### ISSUE TITLE
Is there a way to fully collapse the sidebar?

### ISSUE THREAD

**Issue by weisinlakd** [yaminncco/vue-sidebar-menu#166]
Hi, 
I want to hide the sidebar completely on mobile devices when it is collapsed, and toggle it from an external button.
I've been reading the issues/docs and it seems like there is no option to do so (the fully collapsed bit).
Am I right? Or is there such a feature? If there is not; have you considered adding it, or know any way I can hide it outside of your component?

Edit: tried with `widthCollapsed='0px'` but it leaves a bit of the sidebar visible (tried both on my project and a fresh vue)

Thank you!

**Comment by yaminncco** [comment]
you can hide the sidebar with CSS or using `v-if` `v-show` directive

**Comment by weisinlakd** [comment]
When you set the property ` widthCollapsed='0px'`  it looks like this -> https://i.imgur.com/6aNd13H.png

I may not have been clear in what i want; i wanna have the collapsed state of the sidebar not be visible but to have the regular sidebar available to toggle from a button.

Thanks again!

**Comment by yaminncco** [comment]
did you try with css there's multiple way to do this
```
.v-sidebar-menu {
  transition: 0.3s all;
}
.v-sidebar-menu.vsm_collapsed {
  transform: translateX(-100%);
}
```

**Comment by allburov** [comment]
@yaminncco thank you a lot for creating this great package!

Could you help me - how to expand programmatically the sidebar menu after applying these classes?

**Comment by mariusa** [comment]
@yaminncco I think it would be great to have this built-in. On a mobile phone, the collapsed sidebar takes ~15% of the screen width.

Instead, it would be more useful to have 
1. an API which shows/hides the sidebar (user adds the menu button somewhere in UI, calls this API when clicked)
2. have the sidebar fully hide itself after clicking a menu item, if on mobile

Example: https://freefrontend.com/assets/img/css-mobile-menus/CSS-Mobile-Nav.gif

Thank you!

**Comment by mariusa** [comment]
![CSS-Mobile-Nav](https://user-images.githubusercontent.com/1283842/197271163-47fcea84-2ada-4247-a239-f00cc70d8214.gif)

**Comment by mariusa** [comment]
Solved by using `v-if`
```
<sidebar-menu
            v-if="hasSidebar"
```
