### ISSUE TITLE
Vue 3 + PWA. Can't display utility icons. My bad import method probably.

### ISSUE THREAD

**Issue by MercyLotus** [yaminncco/vue-sidebar-menu#167]
Hello,
I am trying to include this sidebar menu in a blank project. This project has only few dependecies and base PWA configuration.
After some configurations i succeded to import the components and various configurations. 
The sidebar display correctly but i can't see the icons like right-arrow (the webpage displays blank square). In css chrome debugger I saw that classes are set correctly (like content: "|>|" for the span).

I saw from your code that you include fontawesome from 
` <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">`

I tried to install it via npm and I got the right last versions (checkedpackage.json).
I also saw you included rollup plugins. I don't know them: if they are necessary to the sidebar or i could skip them.

I wanted to include this css file locally (present in index.html). I made a folder and placed that file. Then included in main.js. But postcss plugin display an error

`These relative modules were not found:
 ../webfonts/fa-brands-400.eot in ./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/css/fontawesome.all.css ` [...]

Web side:
`Failed to compile.
./src/css/fontawesome.all.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??ref--6-oneOf-3-2!./src/css/fontawesome.all.css)
Module not found: Error: Can't resolve '../webfonts/fa-brands-400.eot' in 'D:\download\VUE prj\test\vuepwa\src\css'`

If useful, I uploaded the app [here](https://drive.google.com/file/d/1p2DL42i40DNkjPGslCHuPT9M9nYgFSdi/view?usp=sharing). 

There are probably more issues in my code. 

If anyone can gives me some advices to include plugins (like this for example): files to be copied, npm module requirements, stuffs to be excluded. I searched on internet some common guidelines to include plugins like this but i didnt find anything short and clear.

I tried to follow installation guide and copy-paste some configurations.

Note:
Novice Vue dev.

Thanks in advance.

**Comment by MercyLotus** [comment]
I finally get it to work.

I downloaded standalone fontawesome 5. I copied missing folder into my project (webfonts).
![image](https://user-images.githubusercontent.com/16444977/102494988-cf684300-4075-11eb-9048-402a2261c508.png)

Then i fixed css import and paths location:
![image](https://user-images.githubusercontent.com/16444977/102495070-ee66d500-4075-11eb-9347-734e0a1096b0.png)
![image](https://user-images.githubusercontent.com/16444977/102495174-11918480-4076-11eb-86b0-587b9a934a4d.png)

I am using default App.vue instead file.html.

All icons and css theme is working.

Just a warning is still present in chrome console:
![image](https://user-images.githubusercontent.com/16444977/102495339-41408c80-4076-11eb-8af2-4bf9b3a26aa3.png)

**Comment by yaminncco** [comment]
the warning is coming from item with custom component either define the component in .vue file or with a render function or config your bundler like the warning said, more info here https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only
