### ISSUE TITLE
Is there a way to close child menu with 'showChild' prop?

### ISSUE THREAD

**Issue by mjk1103** [yaminncco/vue-sidebar-menu#168]
Hi,

I'm looking for an option to show all child menu, and I used 'showChild' prop.
but now I can't close child menu.
Is there a way to close child menu with 'showChild' prop?

Thank :)

**Comment by yaminncco** [comment]
no showChild will always keep child open. what you can do is fork this repo and change [itemShow](https://github.com/yaminncco/vue-sidebar-menu/blob/master/src/components/SidebarMenuItem.vue#L154) to true

**Comment by mjk1103** [comment]
Oh I got it.
Thanks for your comment. :)
