### ISSUE TITLE
Inertiajs workaround dropdown

### ISSUE THREAD

**Issue by raicabogdan** [yaminncco/vue-sidebar-menu#169]
Hello,

I use this sidebar with inertiajs in a laravel project, if you tried using this, you'll notice the active state in sidebar no longer works, and the dropdowns no longer / childs do not show.

My workaround this is as follows:
for siderbar-menu props:
`:showChild="true"`

this will show all dropdowns opened. So from here, its all dom manipulation

```
    beforeUpdate() {
        const parent_vsm_item = document.getElementsByClassName('vsm--item vsm--item_open')
        for(var i=0; i<parent_vsm_item.length; i++){
            // remove the arrow open
            const parent_vsm_item_arrow = parent_vsm_item[i].querySelector('.vsm--arrow_open')
            parent_vsm_item_arrow.classList.remove(this.parents_div.parent_highlight_vsm_arrow)

            // hide dropdown with display none
            const child_dropdown = parent_vsm_item[i].querySelector('.vsm--dropdown');
            child_dropdown.style.display = "none"

            // remove parent background hightlight
            parent_vsm_item[i].classList.remove(this.parents_div.parent_hightlight_vsm_item)
        }

        let open_parent = false

        this.menu.forEach((parent) => {
            if(parent.child != undefined) {
                parent.child.forEach((child_item) => {
                    if (child_item.to == document.URL) {
                        let [parent_id, child_id] = child_item.cid.split('-')
                        if(open_parent == false) {
                            this.parents_div.list[parent_id].classList.add(this.parents_div.parent_hightlight_vsm_item)
                            this.parents_div.list[parent_id].querySelector('.vsm--arrow').classList.add(this.parents_div.parent_highlight_vsm_arrow)
                            this.parents_div.list[parent_id].querySelector('.vsm--dropdown').style.display = 'block'
                            open_parent = true
                        }
                        parent.class = "vsm--item_open"
                        child_item.class = "vsm--link_active"
                    } else {
                        child_item.class = ""
                    }
                })
            } else {
                if (parent.to == document.URL) {
                    parent.class = "vsm--link_active"
                } else {
                    parent.class = ""
                }
            }
        })
    },
    .....
       methods: {
        inertia_navigate(event, item, node) {
            if(item.child instanceof Array) {
                if(!this.parents_div.list[item.id].classList.contains(this.parents_div.parent_hightlight_vsm_item)) {
                    this.parents_div.list[item.id].classList.add(this.parents_div.parent_hightlight_vsm_item)
                    this.parents_div.list[item.id].querySelector('.vsm--arrow').classList.add(this.parents_div.parent_highlight_vsm_arrow)
                    this.parents_div.list[item.id].querySelector('.vsm--dropdown').style.display = 'block'
                } else {
                    this.parents_div.list[item.id].classList.remove(this.parents_div.parent_hightlight_vsm_item)
                    this.parents_div.list[item.id].querySelector('.vsm--arrow').classList.remove(this.parents_div.parent_highlight_vsm_arrow)
                    this.parents_div.list[item.id].querySelector('.vsm--dropdown').style.display = 'none'
                }
            }
            // do not set `to` prop on dropdown parent, only set it on childs. Only childs should navigate
            if(item.to != undefined) {
                this.$inertia.visit(item.to)
            }
        },
    },
    computed: {
            parents_div: function () {
            return {
                list: document.querySelectorAll('.vsm--list > .vsm--item'),
                parent_hightlight_vsm_item: "vsm--item_open",
                parent_highlight_vsm_arrow: "vsm--arrow_open"
            }
        }
    }
```
I also use a menu.js which contains the menu items, where the childs also requires the parent id and child id. The child id is not used, but perhaps it will be useful later...
The child id will contain the parent id so that you can easily get to the parent 
example:

```
        {
            id: 7,
            icon: 'icon-settings',
            title: 'Settings',
            class: "",
            child: [
                {
                    cid: "7-8",
                    to: route('admin.settings'),
                    title: 'General Settings',
                    class: "",
                    icon: 'icon-child',
                },
             ]
         },
```
I know this is just an ugly workaround hack, but I have no idea if its possible to control the dropdown in any other way, if its possible, please do share.

**Comment by yaminncco** [comment]
in the next release you can customize the link component via the use of `linkComponentName` prop, it should cover your use case but this requires upgrading to vue3

**Comment by raicabogdan** [comment]
I tried starting up with vue3, inertia and laravel mix 6 at the beginning, but ended up with a broken setup, got frustrated and started over with vue2 standard setup and worked fine. But its good to know for when things get stable...

**Comment by yaminncco** [comment]
what problem did you face did you use the prop above?
you need to make a custom link component and register it globaly
```
import { createApp, h } from 'vue'

const customLink = (props, { slots }) => {
  const { item, ...attrs } = props
  return h('inertia-link', { ...attrs }, slots.default())
}

const app = createApp(App)
app.component('custom-sidebar-link', customLink)
```

then config the sidebar with the prop
`<sidebar-menu :link-component-name="'custom-link'"/>`

**Comment by raicabogdan** [comment]
Very sorry, that wasn't what I meant. During my initial setup, I attempted to install laravel with vue3 and inertia, for vue3 laravel requires laravel-mix6 which was a beta release at the time, unfortunately when I linked them with inertia, that's where things blowed up and couldn't get it work. It was during a very long night and got frustrated and went with standard setup. It had nothing to do with your sidebar. I just saw that mix6 is now a stable release, perhaps it may work now.

**Comment by raicabogdan** [comment]
Forgive me for my ignorance, but I'm still not sure how using the component helps me?
```
import link from "@inertiajs/inertia-vue3/src/link"
const customLink = (props, { slots }) => {
    const { item, ...attrs } = props
    if(item.href == undefined) {
        return h('a', { ...attrs }, slots.default())
    } else {
        return h(link, { ...attrs }, slots.default())
    }
}
```
This does let me get the inertia-link working from within sidebar directly without calling `@item-click` anymore, however the active state remains the same. Its not updating.

**Comment by yaminncco** [comment]
does the active class apply on init or not? i cant test it right now

**Comment by raicabogdan** [comment]
It is setting `vsm--link_active` on the very first link, so yes.

```<div class="vsm--item">
<a class="vsm--link vsm--link_level-1      vsm--link_active" target="_self" href="http://domain.site/dashboard#"><i class="vsm--icon icon-home"></i><span class="vsm--title">Dashboard</span><!--v-if--><!--v-if--></a><!--v-if-->
</div>```

This is the very first item in menu

**Comment by raicabogdan** [comment]
Sorry, scratch that last one, the active state for the first menu was set in my menu.js file
```
class: "vsm--link_active",
```
thus had the active state by default. I needed to add `class: "" ` so that I can later change it when manipulating dom.

So to answer your question again, its not setting active class on init.

**Comment by raicabogdan** [comment]
A possible solution to this, and works ok on my side.
https://github.com/raicabogdan/vue-sidebar-menu/pull/1/commits/b41179965bdd535cec404db0885da38f81448547

**Comment by yaminncco** [comment]
i released a new patch that should fix the active state on init, the only thing left is when the url change you need to manually call onRouteChange, with inertia something like this can work:

```
const customLink = (props, { slots }) => {
  const { item, ...attrs } = props
  const onRouteChange = inject('onRouteChange')
  return h(link, {
    ...attrs,
    onFinish: () => {
      onRouteChange()
    },
  }, slots.default)
}
```

and make sure to use [persistent layouts](https://inertiajs.com/pages) to prevent the sidebar from re-rendring whenever a link is clicked

**Comment by raicabogdan** [comment]
Works as intended! Just a tip to anyone using this, the href URL's are required to be relative paths. After updating my route() helper to generate them properly the sidebar works correctly.

Issue can be considered resolved, thank you and happy holidays!

**Comment by yaminncco** [comment]
use `showOneChild` prop
