### ISSUE TITLE
How can i pass parameters to my components?

### ISSUE THREAD

**Issue by anamarquezz** [yaminncco/vue-sidebar-menu#17]
I created a method to fill the childs, 
but i want, When the user selects one option of the childs send the id of that child

![imagen](https://user-images.githubusercontent.com/12877909/50484656-7db8e080-09a6-11e9-8ddd-39201bacbad5.png)

pd.: I'm using vue router

![imagen](https://user-images.githubusercontent.com/12877909/50484721-e011e100-09a6-11e9-8ae2-25e3024efb43.png)

**Comment by yaminncco** [comment]
add params to the url

```js
stations.map(function (item) {
    childs.push({
        "href": '/WK/WorkInstruction/'+item.id, // add param
        "title": item.station_name,
        "icon": 'fas fa-minus'
    })
})
```

in routes config

```js
children: [
    path: 'WorkInstruction:id',
    name: 'station',
    component: panelWorkStation
]
```

then you can access id in the `panelWorkStation` component using `$route.params.id`

hope this help.

**Comment by anamarquezz** [comment]
thanks! :tada: !!
