### ISSUE TITLE
Vue 3 version with legacy app

### ISSUE THREAD

**Issue by anielsen** [yaminncco/vue-sidebar-menu#173]
I am trying to use the Vue 3 version

I am integrating it into a legacy app that does some weird stuff the the URLs such as attaching session parameters. When I select an URL say /foo the app might change the URl to /foo?session=abcdefg12345. This means the menu item /foo is not selected in the menu.

I have written af function that will clean the URL for such session related stuff. I would like the menu to use this cleaned up value for comparing with the menu hrefs but it looks like the menu component read the currentRoute directly from the window global and not a prop.

So my question is how do I handle this situation?

I have tried to extend the menu component with

defineComponent({ extends: SidebarMenu, data() { return { currentRoute: cleanedUpUrl } }}) but it doesn't work.

Thanks in advance.

**Comment by yaminncco** [comment]
alias matching is no longer supported without vue-router, temporarily all you can do is to apply the active class through the custom link component

**Comment by tchiotludo** [comment]
@yaminncco does reintroducing the alias previous behaviour can be considered? 
It's really useful for many use case like for examples: 
- having a master menu articles 
- having a detail page article (that can be a alias for vue-router) 
- we want to highlight the articles menu item

**Comment by kirill-malyhin** [comment]
Hello guys! This question is still relevant. @yaminncco , can you provide any easier way how to achieve previous behavior with aliases? Thanks in advance!

**Comment by yaminncco** [comment]
Added `isActive` property in v5.3.0, can work as alias alternative too.

```
{
  href: '/',
  title: 'Dashboard',
  isActive: (item) => {
    // return a boolean to override the active state
  }
}
```
