### ISSUE TITLE
Deployment to Netlify or Vercel

### ISSUE THREAD

**Issue by buildingisfun** [yaminncco/vue-sidebar-menu#174]
Hello @all,

I just found out about 'vue-sidebar-menu' and really like it.

I did 'git clone https://github.com/yaminncco/vue-sidebar-menu.git'.

I made adjustments and it works great on localhost.

I deployed it to Netlify and Vercel ... well, I tried to deploy it.
Both deployments on Netlify and Vercel did NOT work for me.

Normally, I do 
BUILD COMMAND: npm run build
OUTPUT DIRECTORY: dist

Here, this is what made most sense to me:

Vercel
BUILD COMMAND: npm run build:lib
OUTPUT DIRECTORY: dist

Netlify
BUILD COMMAND: npm run build:lib
PUBLISH DIRECTORY: dist

I tried lots of other combinations as well:
BUILD COMMAND: npm run build:lib <-> npm run build:demo <-> npm run build
PUBLISH DIRECTORY: dist <-> demo/dist <-> ./

Can anyone help?

If so, please tell me step by step how to deploy it successfully.

Thanks in advance,

buidlingisfun

**Comment by yaminncco** [comment]
build command is 'npm run build:demo' and the publish directory is the root '/'
