### ISSUE TITLE
Scroll Bar not displaying for sidebar menu

### ISSUE THREAD

**Issue by sushen25** [yaminncco/vue-sidebar-menu#175]
Trying to display a scroll bar for the sidebar dropdown menu but it's not displaying (see attached video)

Using sidebar component in Vue:
```
<sidebar-menu
        :menu="menuItemsJson"
        :collapsed="collapsed"
        theme="white-theme"
        relative
        disable-hover
>
```

My styles to get scrollbar to show:
```
.v-sidebar-menu > .vsm--mobile-item > .vsm--dropdown {
    overflow-y: scroll !important;
}
```

For some reason if I disable the styles in chrome console and turn them on again the scroll bar displays (see attached video)

https://user-images.githubusercontent.com/33281320/108912149-593b1a80-767c-11eb-9927-3c2925c5b46e.mov

**Comment by yaminncco** [comment]
i don't know what the cause is but its seem you are using an old version try to update the lib and see if the issue persists

**Comment by sushen25** [comment]
I've updated the lib and the issue still persists

**Comment by yaminncco** [comment]
is the issue only on touch screen what about testing on different browser or on an actual mobile device
