### ISSUE TITLE
Use with heroicons?

### ISSUE THREAD

**Issue by ncamaa** [yaminncco/vue-sidebar-menu#178]
Is there an easy way to use this library with a completely free-to-use icon library like https://github.com/matschik/vue-hero-icons?
@yaminncco

**Comment by yaminncco** [comment]
yes you can

```
import { AnnotationIcon } from '@vue-hero-icons/outline'

...

icon: {
  element: AnnotationIcon
}
```

element property accept either the name of a registered component, or a component object

**Comment by ncamaa** [comment]
@yaminncco - thanks for the reply. However, I tried this before, and it isn't working for me.
https://pastebin.com/P25nL9fv
![image](https://user-images.githubusercontent.com/25122974/110213285-047f7700-7ea8-11eb-8826-c4eed4fe21ff.png)

**Comment by yaminncco** [comment]
it seems the icons doesn't support vue3

**Comment by ncamaa** [comment]
Thanks! That was the problem. [heroicons for vue 3](https://www.npmjs.com/package/vue-next-heroicons)
