### ISSUE TITLE
Sidebar loading issues.

### ISSUE THREAD

**Issue by jhoopes** [yaminncco/vue-sidebar-menu#179]
Hello, I'm trying to get this to work, and I'm sure there's probably something that I'm partially doing wrong, but can't seem to fully figure out what.

I'm importing the component in my layout component and then adding it to my template with a menu, which seems pretty strait forward, but, it doesn't seem to be working correctly.  I'm on the 5.0.0-alpha.8 version.  It seems the setup function can't get access to the current instance, but when getting that in my layout component and logging it to the console it seems to be able to just fine.  Including the $router property that you're trying to access too.

Is there something i'm missing?  
![image](https://user-images.githubusercontent.com/3297518/110534649-ef435c00-80e4-11eb-8135-e3b465de9c07.png)

the provide errors all trace back to something in the sidebar file.  

This is what the layout component looks like:
![image](https://user-images.githubusercontent.com/3297518/110534922-3b8e9c00-80e5-11eb-8e39-ea729a2cab65.png)

**Comment by yaminncco** [comment]
can you create a minimal repro? what about updating vue

**Comment by yaminncco** [comment]
fixed in v5.0.1
