### ISSUE TITLE
How is it possible to collapse/uncollapse the menu from the application?

### ISSUE THREAD

**Issue by zgyarmati** [yaminncco/vue-sidebar-menu#18]
Maybe it's my mistake, but i couldn't figure out how to toggle the menu from my own code (so not via the menu's own <-> button, but with an other button outside from the menu). I tried to set up v-bind for the 'collapsed' prop, but didn't work. If i set the "isCollapsed" from  them sidebar-menu's data(), then  it almost works: the header text changes to "Main Navigation", but the menu doesn't extend to the 350px width. Is this usecase supported somehow? If yes, is it documented somewhere?

**Comment by yaminncco** [comment]
you can assign a `ref` to the component then call method `toggleCollapse()`
```

<template>
    <sidebar-menu ref="sidebar" />
    <button @click="toggle">toggle</button>
</template>

<script>
export default {
    methods: {
        toggle() {
            this.$refs.sidebar.toggleCollapse()
        }
    }
}
</script>
```

**Comment by zgyarmati** [comment]
Yep, works like a charm, thx!

**Comment by yaminncco** [comment]
in new update you can just toggle `collapsed` prop

**Comment by davodaslanifakor** [comment]
Hi 
@yaminncco   i use this option but don't work for me 
this my code 
```
   <sidebar-menu
      :menu="menu.listMenu"
      :collapsed="collapsed"
      :rtl="true"
      theme="white-theme"
      @item-click="onItemClick"
      @collapse="onCollapse"
    />
```
```
data() {
    return {
      collapsed: true,
....
```
```
 onItemClick(item) {
      this.collapsed = true;
    },```

don't have error and don't work this props 
my -v sidebar =>  "vue-sidebar-menu": "^3.11.1",

**Comment by yaminncco** [comment]
@davodaslanifakor in your code collapse is always true, i am not sure what doesn't work and what are you trying to achieve?
