### ISSUE TITLE
Icons are not getting displayed

### ISSUE THREAD

**Issue by Mageswaran1989** [yaminncco/vue-sidebar-menu#184]
I followed the README steps, however for some reasons, the icon area is black. Thanks!
![image](https://user-images.githubusercontent.com/3304549/114714171-7a042000-9d4f-11eb-9276-be1938a55b17.png)

**Comment by thegostisdead** [comment]
You need to Install fonts and import them.
Look this closed issue https://github.com/yaminncco/vue-sidebar-menu/issues/20

**Comment by Mageswaran1989** [comment]
Install the package using `yarn add @fortawesome/fontawesome-free` and in `main.js` add :  
`import @fortawesome/fontawesome-free/css/all.css`

**Comment by mara-vicentina** [comment]
Install @fortawesome/fontawesome-free

Then import css
import '@fortawesome/fontawesome-free/css/all.css'

And also import js
import '@fortawesome/fontawesome-free/js/all.js'

You really dont need vue-fontawesome, it took me a while to understand this.
