### ISSUE TITLE
position: static bar does not display hovered:collapsed menu properly

### ISSUE THREAD

**Issue by sanibelle** [yaminncco/vue-sidebar-menu#185]
I tried to changed the position of the bar to `static` in CSS to adapt it to my layout with grid.

When I use the collapsed bar, the menu text that appears on hover has an offset equal to the distance to the top of the page. So basically, if the navbar is `50px` from top, the menu on hover text is `50px` higher than it's supposed to be.

I guess that it would be nice to have a static position support.

**Comment by yaminncco** [comment]
use position relative instead of static, or you can use relative prop

**Comment by sanibelle** [comment]
It works, sorry, it was my mistake, i forgot to remove 
`position: static !important;` from my CSS.

Thx for the quick answer
