### ISSUE TITLE
I'm trying to use a custom svg icon for the sidebar but it's not appearing

### ISSUE THREAD

**Issue by Rishi-Bidani** [yaminncco/vue-sidebar-menu#187]
```
        {
          href: "/",
          title: "Custom Icon",
          icon: {
            element: "img",
           attributes: {
              src: "./assets/customicon.svg",
              alt: "Custom Icon",
            },
          },
        },
```

**Comment by yaminncco** [comment]
create an svg icon component or you can use vue-svg-loader

**Comment by Rishi-Bidani** [comment]
@yaminncco I found an easier solution which seems to work. I've just started learning vuejs so I didn't want to confuse myself with complicated features like vue-svg-loader, even if it might be useful later on. I'm also attaching an image of it working
![image](https://user-images.githubusercontent.com/64310471/118392576-f85a2780-b657-11eb-80d2-a447fe98fe9e.png)


You can just require the svg icon and use it as follows

```
const customSvG= require("./assets/customSVG.svg");

        {
          href: "/",
          title: "New SVG",
          icon: {
            element: "img",
            attributes: {
              src: customSVG,
              // alt: "new Folder",
            },
          },
        },
```
Anyway thank you for your reply, it certainly directed me in the correct direction for finding this.
