### ISSUE TITLE
How to disable router-link

### ISSUE THREAD

**Issue by Rishi-Bidani** [yaminncco/vue-sidebar-menu#189]
I'm using the side bar as buttons with my own methods, everything is working fine but I keep getting this warning. I'm not using the href parameter.
![image](https://user-images.githubusercontent.com/64310471/120076376-d1254080-c0c2-11eb-9cac-92a0348666ca.png)

**Comment by yaminncco** [comment]
without vue-router you need to make a custom link, check doc https://github.com/yaminncco/vue-sidebar-menu/tree/next#customize-link

**Comment by Rishi-Bidani** [comment]
> without vue-router you need to make a custom link, check doc https://github.com/yaminncco/vue-sidebar-menu/tree/next#customize-link

I apologize, but what custom link will I have to enter if I'm not using href at all?

**Comment by yaminncco** [comment]
you can render an hyperlink
```
const customLink = {
  name: 'CustomLink',
  props: ['item'],
  render() {
    return h('a', this.$slots.default())
  }
}
```

**Comment by Rishi-Bidani** [comment]
@yaminncco Thank you so much for your quick response. This is working well.
