### ISSUE TITLE
Please allow us to have href on parent item

### ISSUE THREAD

**Issue by KiloMikeCodesStuff** [yaminncco/vue-sidebar-menu#19]
Hi, I have the following:

![image](https://user-images.githubusercontent.com/24838603/50676628-77cb9b00-1049-11e9-8a63-07c270adf697.png)

If I click `btn-primary`, `btn-secondary` etc, it will navigate to them fine.

However, I wish I could also click `Buttons` to navigate to the `Buttons` section, or `Bootstrap` to navigate to the `Bootstrap` section. It appears that setting `href` for any item with `child` set will not take effect.

If you could implement this, it would be perfect!

Thank you!

**Comment by yaminncco** [comment]
fixed in v3.1.0

**Comment by KevinMallinson** [comment]
Hi @yaminncco not sure if this is a regression or not, however after updating, and having a `href` attribute while also having a `child` attribute, makes it impossible to navigate to those children:

![image](https://user-images.githubusercontent.com/46643032/51448236-3f31fe00-1d79-11e9-98fb-52be382bb36f.png)
![image](https://user-images.githubusercontent.com/46643032/51448248-57a21880-1d79-11e9-927d-9ebbd77f5380.png)
