### ISSUE TITLE
error with vue 3.2.0-beta.7: provide() can only be used inside setup

### ISSUE THREAD

**Issue by mariusa** [yaminncco/vue-sidebar-menu#194]
Hi,

sidebar-menu 5.0.0 works great with vue 3.1.x with `<script setup>` syntax

I tried vue 3.2.0-beta.7 and I get an error:
```js
vue-sidebar-menu.js [Vue warn]: provide() can only be used inside setup
Unhandled error during execution of setup function 
  at <SidebarMenu menu=
vue-sidebar-menu.js?v=0275664f:4609 Uncaught (in promise) TypeError: Cannot read property 'appContext' of null
    at setup (vue-sidebar-menu.js
```

Would you please have a look and see if the cause is vue? And if so, would you please report the bug at vue-next?
Thanks!

**Comment by yaminncco** [comment]
related issue #179, fixed in v5.0.1
