### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by pieroliviermarquis** [yaminncco/vue-sidebar-menu#196]
I get this error when using it with Vuejs2:

```
vue-sidebar-menu.esm.js?2ab6:3 Uncaught TypeError: Object(...) is not a function
    at eval (vue-sidebar-menu.esm.js?2ab6:3)
```

The problem is with ref below:
`var isCollapsed = ref(false);`

**Comment by yaminncco** [comment]
v5.x only support vue3, if you want to use vue2 refer to the [doc](https://github.com/yaminncco/vue-sidebar-menu/tree/master)
