### ISSUE TITLE
[Vue warn]: Failed to resolve component: router-link

### ISSUE THREAD

**Issue by eXCom** [yaminncco/vue-sidebar-menu#199]
Im getting warnings in fresh laravel application. Everything is working but would be nice to get rid of them, any ideas ?
![123](https://user-images.githubusercontent.com/5220521/133088172-a3faadb4-2436-4a13-a61e-c12856f15b25.png)

**Comment by yaminncco** [comment]
without vue-router you need to provide a custom link component, check documentation https://github.com/yaminncco/vue-sidebar-menu#customize-link

**Comment by eXCom** [comment]
That worked for me, thank you!

**Comment by eXCom** [comment]
Im sorry, i didnt notice at first, it did removed the warnings but now the sidebar stopped working, when im trying to expand a menu options with children options im getting an error :(

![123](https://user-images.githubusercontent.com/5220521/133282550-bfaa68fa-fc14-40d4-b0d1-7c225c66c874.png)

**Comment by yaminncco** [comment]
can you provide a minimal reproduction

**Comment by yaminncco** [comment]
its an issue with inertiajs i recommend to use [persistent-layouts](https://inertiajs.com/pages#persistent-layouts)

**Comment by yaminncco** [comment]
fixed the error in v5.1.0
