### ISSUE TITLE
Icons don't show

### ISSUE THREAD

**Issue by thibaultchazal** [yaminncco/vue-sidebar-menu#20]
Hi

I can not figure to have the icons appear. I've tried to install globally and locally. Everything works except the icons
Also the css files didn't install in the node_modules/vue-sidebar-menu folder. I have to add them manually. May be the cause ?

Thanks in advance

**Comment by yaminncco** [comment]
icons not showing are you using font-awesome in your project?
and about the css file, you need to update to the latest version v3.

**Comment by dacoders77** [comment]
No icons at all.

**Comment by nmbabor** [comment]
Use it in your style. 
.v-sidebar-menu .vsm-arrow:after{font-family: FontAwesome}
  .v-sidebar-menu .collapse-btn:after {
    content: "\f07e";
    font-family: FontAwesome;
  }

**Comment by yaminncco** [comment]
it looks like you're not using font-awesome v5 so replace `fas` with `fa`

**Comment by thibaultchazal** [comment]
I am using font-awesome v5
`    "@fortawesome/fontawesome-svg-core": "^1.2.12",
    "@fortawesome/free-solid-svg-icons": "^5.6.3",
    "@fortawesome/vue-fontawesome": "^0.1.4",`

Maybe is the way I use it ? I follow font-aweosme guide use for vue :
`import { library } from '@fortawesome/fontawesome-svg-core'
import { faCoffee } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
library.add(faCoffee)
Vue.component('font-awesome-icon', FontAwesomeIcon)`

**Comment by yaminncco** [comment]
install `@fortawesome/fontawesome-free`

then import css
`import '@fortawesome/fontawesome-free/css/all.css'`

you dont need vue-fontawesome

**Comment by hjelperne** [comment]
Hi,

Would it be possible to somehow add support for vue-fontawesome - so one can benefit from not including the enitre font-awsome library in all.css - as suggested above - but rather select which icons to bundle as the vue-font-awsome supports (as described by @thibaultchazal).

**Comment by timmalich** [comment]
It would be awesome if the demo could provide the "import '@fortawesome/fontawesome-free/css/all.css'" information as well as the package.json :-)

**Comment by mara-vicentina** [comment]
Install @fortawesome/fontawesome-free

Then import css
import '@fortawesome/fontawesome-free/css/all.css'

And also import  js 
import '@fortawesome/fontawesome-free/js/all.js'

You really dont need vue-fontawesome, it took me a while to understand this.
