### ISSUE TITLE
Hide Menu Options based on computed value: Example: When not logged in

### ISSUE THREAD

**Issue by robert-jf-close** [yaminncco/vue-sidebar-menu#201]
When a user is logged in, I want to show more menu options. I see the "hidden" attribute can be set true or false, but not reactively. Is there a way to hide menu items based on other variables?

**Comment by yaminncco** [comment]
you can make the menu computed

**Comment by robert-jf-close** [comment]
No, that does not work. The binding is not correct. The computed value does not change the displayed value. Try this... 
`      menu: [
        {
          header: "Navigation",
          hiddenOnCollapse: true,
        },
        {
          header: "Admin",
          hiddenOnCollapse: true,
          hidden: this.hideAdminBoard,
        },
},
computed: {
showAdminBoard() {
return false;
},`

**Comment by ala747** [comment]
@robert-jf-close, I think he mean to make the whole menu computed, something like this:

```
computed: {
  menu() {
    return [
      {
        header: "Navigation",
        hiddenOnCollapse: true
      },
      {
        header: "Admin",
        hiddenOnCollapse: true,
        hidden: this.hideAdminBoard
      }
    ]
  },
  hideAdminBoard() {
    return !this.isAuthenticated // or the store/var/whatever you use to know if the user is logged in or not
  }
}
```

**Comment by robert-jf-close** [comment]
@ala747, that makes more sense.... :facepalm  Thank you.
