### ISSUE TITLE
disableHover not supported in Vue 3

### ISSUE THREAD

**Issue by thovu162020** [yaminncco/vue-sidebar-menu#204]
In component [SideBarMenu](https://github.com/yaminncco/vue-sidebar-menu/blob/next/src/components/SidebarMenu.vue) in branch `next`, the prop `disableHover` is declared but never used, unlike in same component in branch `master`.

Might I ask for support for this prop?

**Comment by yaminncco** [comment]
disableHover is working in vue3, the prop is used in the composition function https://github.com/yaminncco/vue-sidebar-menu/blob/next/src/use/useItem.js
