### ISSUE TITLE
How to Remove the animation on mounted for the active menu group?

### ISSUE THREAD

**Issue by cristian-fastfwd** [yaminncco/vue-sidebar-menu#208]
Hi, 
I am using this plugin on a server side rendered app. So, every page visit, the whole page reloads and the menu is mounted every time. I wanted to remove the unfurling animation for the selected menu group. Basically, I want the active menu group to be already opened when the page loads. Do you have any suggestion how to do this?

**Comment by yaminncco** [comment]
can you make a minimal reproduction? the transition should not work on initial load

**Comment by cristian-fastfwd** [comment]
I'm doing this to force the menu group to open on initial load.
```
mounted() {
        let openMenuGroup = this.getOpenMenuGroup(this.menu_list);
        if (openMenuGroup) {
            this.$refs.sideBarMenu.activeShow = openMenuGroup;
        }
    },
```

**Comment by cristian-fastfwd** [comment]
Closing this issue. 
I was able to remove the animation by overriding these classes on initial load

```

    .expand-enter-active,
    .expand-leave-active {
      transition: height 0.3s ease;
      overflow: hidden;
    }
    .expand-enter-from,
    .expand-leave-to {
      height: 0 !important;
    }

    .slide-animation-enter-active {
      transition: width 0.3s ease;
    }
    .slide-animation-leave-active {
      transition: width 0.3s ease;
    }
    .slide-animation-enter-from,
    .slide-animation-leave-to {
      width: 0 !important;
    }

```
