### ISSUE TITLE
How to place an image on header to sidebar

### ISSUE THREAD

**Issue by wapewape** [yaminncco/vue-sidebar-menu#21]
![github](https://user-images.githubusercontent.com/1838797/50977296-c311fd80-14d0-11e9-89fa-8e7e04cca0cf.png)

Hi, i need add an image in header to sidebar, How could I do it?
Thx

**Comment by yaminncco** [comment]
currently you cant but i am working on this

**Comment by yaminncco** [comment]
in v3.2.0 you can add img like this
```
const logoImg = {
    data() {
        return {
            src: 'path/to/image'
        }
    },
    template: '<img :src="src">'
}

export default {
    ...
    menu: [
        {
            header: true,
            component: logoImg
        }
    ]
    ...
}
```

**Comment by YaseenHajajweh** [comment]
@yaminncco, I am using V3 and followed your comment that regarding the header logo, it's not working
