### ISSUE TITLE
How supported for i18n?

### ISSUE THREAD

**Issue by codedaily** [yaminncco/vue-sidebar-menu#210]
Hi~ 
I'm looking closely at your project.
First, I would like to express my gratitude.

I want to develop i18n.
How supported for i18n?

**Comment by yaminncco** [comment]
Should work fine, do you have any problem?

**Comment by tarikkavaz** [comment]
@codedaily 
```
{
  href: '/products',
  title: `${this.$t("products")}`,
  icon: 'fa-solid fa-bag-shopping',
},
```

**Comment by yaminncco** [comment]
Closing since there is no issue
