### ISSUE TITLE
[Help] How can I show all children at start while still make all sub-menu able to show/hide?

### ISSUE THREAD

**Issue by Paper-Folding** [yaminncco/vue-sidebar-menu#213]
The problem is, currently when I set `showChild` property to `true` it makes all children shown at start, that's good! But also prevent sub-menus from being hide.
Is there any way to still make sub-menu able to toggle show/hide while remain `showChild` property being set to `true`?

**Comment by yaminncco** [comment]
Sorry but there's no option for this and i cant think for a workaround, but its something that possible to implement.

**Comment by Paper-Folding** [comment]
> Sorry but there's no option for this and i cant think for a workaround, but its something that possible to implement.

That's fine, I am currently using a compromise approach: by expanding all sub-children when user enters page, and then collapsing the children after two seconds.

And thank you for your sidemenu that saves my day: I do really really appreciate that you implemented the sub-children and sub-sub-children and sub-sub-sub-children items! What an awesome recursion!
