### ISSUE TITLE
Problem with closing animation of width

### ISSUE THREAD

**Issue by brunsforge** [yaminncco/vue-sidebar-menu#215]
The sidebar wont animate the width correctly on close. I tried same menu items with white or default theme, without my modifications and so on but i cannot determine what causes it. On opening the width from (my min is 50px and max is 300) is animated correctly). I only edited the theme scss. Any ideas? It positioned relative

![navanimation](https://user-images.githubusercontent.com/5312061/150297522-f33356f5-2a90-4c9b-b5e3-cc8fd0be0f65.gif)

EDIT: I am using it in an auto sized grid column, that seems to make the difference. Not related to the sidebar itself!

**Comment by yaminncco** [comment]
Quick fix for this is to add width transition, here is an example:

```html
<template>
  <div class="grid">
    <sidebar-menu relative />
    <div>content</div>
  </div>
</template>

<style>
.grid {
  display: grid;
  grid-template-columns: min-content 1fr;
}
.grid .v-sidebar-menu .vsm--scroll>.vsm--menu {
  transition: 0.3s width ease;
}
</style>
```

**Comment by brunsforge** [comment]
> Quick fix for this is to add width transition, here is an example:
> 
> ```
> <template>
>   <div class="grid">
>     <sidebar-menu relative />
>     <div>content</div>
>   </div>
> </template>
> 
> <style>
> .grid {
>   display: grid;
>   grid-template-columns: min-content 1fr;
> }
> .grid .v-sidebar-menu .vsm--scroll>.vsm--menu {
>   transition: 0.3s width ease;
> }
> </style>
> ```

Wow - thank you for that response. Indeed - with that additional transition i can use it in my grid layout without having to change anything else
![layout2](https://user-images.githubusercontent.com/5312061/150382911-40280c2c-cd37-4005-a61d-7433d47b7c2a.gif)
!
