### ISSUE TITLE
Bug with setting position to realtive?

### ISSUE THREAD

**Issue by brunsforge** [yaminncco/vue-sidebar-menu#216]
If i set the sidebar menu to relative=true there seems to be a problem with the width on collapsed dropdown items. If i change position fixed to relative in the base layout instead of setting the relative property on the component it works as expected.

![image](https://user-images.githubusercontent.com/5312061/150305828-00bddff3-d120-442c-911f-59a4da383ce8.png)

**Comment by yaminncco** [comment]
Here the sidebar is relative to `.sidebar_left` and not your grid. remove .sidebar_left.
Check my working [example ](https://github.com/yaminncco/vue-sidebar-menu/issues/215#issuecomment-1017443899)on how to use the relative prop in a grid layout
