### ISSUE TITLE
Example use of "onRouteChange" to set active state

### ISSUE THREAD

**Issue by fer-ri** [yaminncco/vue-sidebar-menu#217]
Hi

Could you give an example of this

> Note: the "onRouteChange" function can be injected useful for updating the active state whenever the url change.

I'm using Inertia Link as a custom link and I want to set active for nested links

- /users => I want to make it "active"
- /users/1/edit ==> **current**

Thanks

**Comment by yaminncco** [comment]
The active class is applied only if the current route is exactly the same as the item route,
So for nested routes be active you need to add the active class either from the menu prop or from the custom link component, here's an example:
```js
const customLink = {
  name: 'CustomLink',
  props: ['item'],
  render() {
    return h(link, {
      class: this.$page.url.startsWith(this.item.href) && 'vsm--link_active',
    }, this.$slots.default)
  },
  watch: {
    '$page.url' () {
      this.onRouteChange()
    }
  },
  inject: ['onRouteChange']
}
```
Note by doing this, features like auto open child menu when parent is active won't work.

**Comment by fer-ri** [comment]
Thanks for the help :pray: 

> Note by doing this, features like auto open child menu when parent is active won't work.

Ok, no problem :smile: 

btw Awesome package :+1:
