### ISSUE TITLE
Hiding scrollbar

### ISSUE THREAD

**Issue by SciManJD** [yaminncco/vue-sidebar-menu#218]
For some reasons the scrollbar in my application is visible without to be needed. Is there a way to disable the scrollbar at all?

**Comment by yaminncco** [comment]
Can you provide more details like does the issue persists in an different browser?

**Comment by SciManJD** [comment]
Strange... I didn't expect that this depends on the browser, but it is so... Normally I use Firefox and I see the scrollbar. I made test with Edge and the scrollbar doesn't exist. What else you want to know?

**Comment by yaminncco** [comment]
Zooming out is the cause for the scrollbar to appear.

**Comment by SciManJD** [comment]
Yes, you are right. I saw that the zoom was set to 90%. When I made it again 100%, the scrollbar disappeared. But is there a way to disable the scrollbar completely?

**Comment by yaminncco** [comment]
Temporary css fix:
```
.v-sidebar-menu .vsm--scroll {
  width: calc(100% + 100px);
}
```

**Comment by SciManJD** [comment]
Thanks a lot. This fix works fine.
