### ISSUE TITLE
Changing the color of theline that marks the selected menu

### ISSUE THREAD

**Issue by SciManJD** [yaminncco/vue-sidebar-menu#219]
Hi! I tried almost everything, but I couldn't find a way to change the color of the blue line that marks the selected menu. How can I do this?

**Comment by yaminncco** [comment]
You need a higher specificity or use !important
```
.v-sidebar-menu .vsm--link_level-1.vsm--link_active {
  box-shadow: 3px 0px 0px 0px red inset !important;
}
```

**Comment by SciManJD** [comment]
Thanks a lot. This is exactly what I need.
