### ISSUE TITLE
keep header on collapse mode

### ISSUE THREAD

**Issue by yonarbel** [yaminncco/vue-sidebar-menu#22]
sometime I'd like to keep the header on collapse for example if I have an icon that i want to keep on collapse mode just in a smaller dimension, it would be awesome to have the option add on the header item a prop like "visibleOnCollapse" so if its true, the header item will get rendered even on collapsed

**Comment by yaminncco** [comment]
added in v3.3.0

**Comment by nikola-pavlovic** [comment]
How exactly to use this...please document

**Comment by yonarbel** [comment]
just add visibleOnCollapse:true 
on the sidebar item
