### ISSUE TITLE
Collapse toggle event issue

### ISSUE THREAD

**Issue by corey-calhoun** [yaminncco/vue-sidebar-menu#220]
I have imported this into a project that is using CoreUI and now the toggle events are not working as the demo. It seems as if maybe it's getting partially overridden or confused by the UI kit. Is this something you have experienced or have a suggestion for work around? I renamed the collapse method but still no fix.

**Comment by yaminncco** [comment]
Can you provide a minimal reproduction, otherwise why not use coreui sidebar?
