### ISSUE TITLE
Icon size is not working with vue-fontawesome

### ISSUE THREAD

**Issue by vsirghii** [yaminncco/vue-sidebar-menu#222]
**Need help with icon sizing, icons appear to be too big:**

![image](https://user-images.githubusercontent.com/26068474/159112955-bc3c1962-1cdb-48d9-b80a-31a51dbdcc58.png)

**Compare with this repo's demo, my icons above are too big:**

![image](https://user-images.githubusercontent.com/26068474/159113144-72e29ea6-da25-46b2-a3c6-9d701bf45bd8.png)

**Here is my code:**

![image](https://user-images.githubusercontent.com/26068474/159113084-f2cb0d21-6568-48d1-bd00-1b1987d69940.png)

**As you can see, `rotation ` attribute works, but `size` doesn't (whatever values I'm trying)**

**Here are my settings:**
```
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret, faCode, faDownload } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
library.add(faUserSecret, faCode, faDownload)
```

**And this is from INSPECT view:**

![image](https://user-images.githubusercontent.com/26068474/159114172-d330003f-9732-4c9d-8ee7-f1975b6688be.png)

Notice that icon renders via `svg `(not `i` or `font-awesome-icon`). Might it be that the size isn't working due to `svg`???

**Comment by yaminncco** [comment]
Size doesn't work cause the icon have a fixed width & height so you need to change that in css
here a css fix to your problem

```
.v-sidebar-menu .vsm--link_level-1 .vsm--icon {
  padding: 5px;
  box-sizing: border-box;
}
```

**Comment by vsirghii** [comment]
Thank you!
