### ISSUE TITLE
How can I change the background color of an item when hovering?

### ISSUE THREAD

**Issue by hcli09** [yaminncco/vue-sidebar-menu#226]
![image](https://user-images.githubusercontent.com/93247587/163674089-93c14021-093d-4e4f-9bb4-db839faeec3d.png)
![image](https://user-images.githubusercontent.com/93247587/163674291-5ce55c7e-3bb4-4bda-847b-21b72d8e2495.png)

As per the title, I haven't found a way to solve this. I have tried the following on the vue component:
```
.v-sidebar-menu.vsm_white-theme.vsm_collapsed .vsm--link_level-1.vsm--link_hover .vsm--icon {
    background-color: #24292f !important;
}
```
which doesn't work.

Also, trying to change the vars in the `_variable.scss` doesn't work. 

Last, any insights that I can change the theme variables would be appreciated. I have gone over the instruction but still don't know where I should put the following line for example: 
```
$primary-color: #24292f !default;
@import "vue-sidebar-menu/src/scss/vue-sidebar-menu.scss";
```
if I just want to change the primary color.

**Comment by yaminncco** [comment]
The selector is `.vsm--mobile-bg`
For the theme you can import it in the main.js file

**Comment by hcli09** [comment]
Interesting, I don't think both approaches can work on my end.

The first thing I tried was to write the following code on _the component using the_ `vue-sidebar-menu`: 
![image](https://user-images.githubusercontent.com/93247587/163939321-4e2418cc-63b1-4618-a06d-69ca26c4e5ff.png)
This doesn't work.

Another thing was overriding the variables in the `main.js`:
![image](https://user-images.githubusercontent.com/93247587/163939769-6f46fb7e-0dee-4c43-88b4-d9d916dff4d2.png)
![image](https://user-images.githubusercontent.com/93247587/163939801-af5324d4-e681-4186-b49a-e308b4340af8.png)
![image](https://user-images.githubusercontent.com/93247587/163940637-1b2a6b0d-ac75-4d92-8e10-b47581efb1bb.png)

Is there anything I should change to make it work?

**Comment by yaminncco** [comment]
First doesn't work cause style has scoped attribute, and to override with css try to use a more specific selector.
```
<style lang="scss">
.app .v-sidebar-menu .vsm--mobile-bg {
  background-color: red;
}
</style>
```

For the second issue you need to import `vue-sidebar-menu/src/scss/vue-sidebar-menu.scss` after overriding the variables.

```
$primary-color: red;
@import "vue-sidebar-menu/src/scss/vue-sidebar-menu.scss";
```

And you don't need to import the css file.

**Comment by hcli09** [comment]
The second finally works! Thanks!
