### ISSUE TITLE
Automatically close sidebar on mobile when submenu item is clicked

### ISSUE THREAD

**Issue by sebastian-raubach** [yaminncco/vue-sidebar-menu#227]
Currently, when on mobile, the sidebar won't automatically close when a submenu item is selected. This comment (https://github.com/yaminncco/vue-sidebar-menu/issues/165#issuecomment-778600775) suggests that this is intentional to prevent accidental click closes.

But how would I change it so that it does close when a submenu item is selected? At the moment people navigate to a different page, but may not notice that it was successful, because the submenu covers most of the screen.

**Comment by yaminncco** [comment]
I'll try to implement or provide a solution for this.

**Comment by yaminncco** [comment]
Added this as default behavior in v5.2.4.

**Comment by sebastian-raubach** [comment]
Nice job! Any chance to get this backported to the vue2 branch?
