### ISSUE TITLE
[Vue 2] Custom scrollbar 

### ISSUE THREAD

**Issue by timbrand** [yaminncco/vue-sidebar-menu#229]
Is there a possibility for a custom scrollbar in the Vue 2 variant of this component?

**Comment by yaminncco** [comment]
No plan to add this to the vue2 version, For the moment you can you can fork and add the scrollbar component [here](https://github.com/yaminncco/vue-sidebar-menu/blob/next/src/components/SidebarMenuScroll.vue).
