### ISSUE TITLE
Feature Request: Please provide the ability to pass a boolean to disallow shrinking the sidebar

### ISSUE THREAD

**Issue by KevinMallinson** [yaminncco/vue-sidebar-menu#23]
Hi, I don't need the sidebar to be shrunk, since i'm not using any icons. In this event, I don't want it to be allowed to be shrunk. Can you please make a condition so we can disallow shrinking?

Thanks

**Comment by yaminncco** [comment]
All you have to do is hide collapse-btn with css 

```
.v-sidebar-menu .collapse-btn {
    display:none;
}
```

**Comment by KevinMallinson** [comment]
Hi, it works. However I think it would be good to have a flag :hidden="true" or something, that way we don't need to modify the css. 

Closing, thanks.
