### ISSUE TITLE
push version 5.x to master branch

### ISSUE THREAD

**Issue by mariusa** [yaminncco/vue-sidebar-menu#230]
Hi,

`npm outdated` shows
```
Package                 Current         Wanted  Latest  Location                       Depended by
vue-sidebar-menu          5.2.2          5.2.2   4.8.1  node_modules/vue-sidebar-menu  admin
```
(Latest is 4.8)

I think because version 5.x is still on the 'next' branch.

Would you please push version 5.x to master branch? One can always use vue2 version by putting `vue-sidebar-menu: 4.x.x` in package.json

Thanks!

**Comment by yaminncco** [comment]
Done.

**Comment by mariusa** [comment]
Thank you!
