### ISSUE TITLE
Can I use Hericon ?

### ISSUE THREAD

**Issue by stoneC0der** [yaminncco/vue-sidebar-menu#232]
I tried to use hericon but can figure out how to implement that
can you point me to the right direction if that's doable and simple or my just sweet to compatible icon libraries

Thanks!

**Comment by yaminncco** [comment]
Icon property with a custom component:

```
import myIcon from './myIcon.vue'

// menu
{
  icon: {
    element: myIcon
  }
}
```

**Comment by stoneC0der** [comment]
Thanks a lot.
