### ISSUE TITLE
how to move a menu item to the bottom

### ISSUE THREAD

**Issue by anubisg1** [yaminncco/vue-sidebar-menu#234]
How can i move an entry at the bottom of the menu ?
for example i'd like to move the "settings" menu entry at the bottom of the screen

**Comment by yaminncco** [comment]
We can achieve this with flex and margin-top auto.
First add css flex to the menu
```
.v-sidebar-menu .vsm--menu {
  display: flex;
  flex-direction: column;
  height: 100%;
}
```

Then create a component that push everything that comes after it to the bottom
```
import { h, markRaw } from 'vue'
const pushToBottom = markRaw({
  render: () => h('div'),
  mounted () {
    const itemEl = this.$el.parentElement
    itemEl.style.marginTop = 'auto'
  }
})

menu: [
  ...
  {
    component: pushToBottom
  },
  {
    title: 'Settings'
  }
]
```

**Comment by anubisg1** [comment]
oh thanks a lot! let me try that out!

**Comment by anubisg1** [comment]
it works perfectly! thank you 

![image](https://user-images.githubusercontent.com/4518931/174082777-b7a829d5-fed3-4307-87bc-cff33b6934df.png)
