### ISSUE TITLE
add some animation to  .collapse-btn

### ISSUE THREAD

**Issue by nikola-pavlovic** [yaminncco/vue-sidebar-menu#24]
Hi, great work...please continue :)

It would be great if we could use our own icon inside `.collapse-btn `, and add some simple animation for... using slots, right.

![sidebar-colapsebutton](https://user-images.githubusercontent.com/46919333/51523656-78777600-1e2c-11e9-9562-cd5333690aec.gif)

I can not use font awesome in my project, instead I am using `<i class="...icon-ios-arrow-back"></i>`, which is easier to animate then `.collapse-btn::after` .

**Comment by yaminncco** [comment]
you can still use `.v-sidebar-menu.vsm-collapsed` class to animate

```
.v-sidebar-menu .collapse-btn:after {
    display: block;
    transition: 0.3s transform;
}

// on collapse
.v-sidebar-menu.vsm-collapsed .collapse-btn:after {
    transform: rotate(90deg);    
}
```
