### ISSUE TITLE
when using Inertia open current link but not slide down children

### ISSUE THREAD

**Issue by ushter27** [yaminncco/vue-sidebar-menu#240]

**Comment by ushter27** [comment]
<template>
    <sidebar-menu :link-component-name="'custom-link'" :menu="menu" />
</template>

<script setup>
        const menu = [
                {
                    header: 'Main Navigation',
                    hiddenOnCollapse: true
                },
                {
                    href: '/users',
                    title: 'Dashboard',
                    icon: 'fa fa-user'
                },
                {
                    title: 'Charts',
                    icon: 'fa fa-chart-area',
                    child: [
                        {
                            href: '/charts/sublink',
                            title: 'Sub Link'
                        },
                        {
                            href: '/charts/edit',
                            title: 'Products'
                        }
                    ]
                }
            ];
</script>

**Comment by ushter27** [comment]
`<template>
    <sidebar-menu :link-component-name="'custom-link'" :menu="menu" />
</template>

<script setup>
        const menu = [
                {
                    header: 'Main Navigation',
                    hiddenOnCollapse: true
                },
                {
                    href: '/users',
                    title: 'Dashboard',
                    icon: 'fa fa-user'
                },
                {
                    title: 'Charts',
                    icon: 'fa fa-chart-area',
                    child: [
                        {
                            href: '/charts/sublink',
                            title: 'Sub Link'
                        },
                        {
                            href: '/charts/edit',
                            title: 'Products'
                        }
                    ]
                }
            ];
</script>`

**Comment by yaminncco** [comment]
Not sure if i understand the issue but this might help you https://github.com/yaminncco/vue-sidebar-menu/issues/183#issuecomment-808902983
