### ISSUE TITLE
Similar URLs set active together

### ISSUE THREAD

**Issue by MarlonEtiene** [yaminncco/vue-sidebar-menu#246]
Hello again!

I used answer #217 and it worked fine, but I have very similar url's like `account` and `account-type`.
When I click on the menu item that the href is `account`, only that item is set as active, however, if I click on the item that the href is `account-type`, both items are seted as active.
I tried a few ways to not set both as active, but in all I was not successful.
I know this is not a component problem, probably a javascript failure of mine, however, could you help me please?
Anyway, thanks and sorry for my bad english

**Comment by yaminncco** [comment]
Add `/` at the end:
`this.$page.url.startsWith(this.item.href+'/')`

**Comment by MarlonEtiene** [comment]
@yaminncco you are a genius!
Worked like a charm!
Thank you so much!
