### ISSUE TITLE
[help] hidden hr separator

### ISSUE THREAD

**Issue by ILOG9** [yaminncco/vue-sidebar-menu#248]
I have tried to add an hr to separate the elements as indicated by the demo folder, however it does not work

and here is an example of use

`const menu = [
    {
        component: {
          template: '<hr style="border-color: rgba(0, 0, 0, 0.1); margin: 20px;">'
        }
    }
]`

As you navigate through the code, you can see that the li tag that corresponds to the component position in the array appears with a comment.

note: for the above example i have replaced `` with '' so that github doesn't break

Thanks for the help!

**Comment by yaminncco** [comment]
Can you show more code, do you have any error/warn?

**Comment by yaminncco** [comment]
You can use render function
```js
import { h } from 'vue'
const separator = h('hr', {
  style: {
    borderColor: 'rgba(0, 0, 0, 0.1)',
    margin: '20px'
  }
})
```

**Comment by ILOG9** [comment]
That was exactly what I needed, thanks for your time
