### ISSUE TITLE
create option to have only one item collapsed at the same time

### ISSUE THREAD

**Issue by nikola-pavlovic** [yaminncco/vue-sidebar-menu#25]
Hi again,
Could you add prop for allowing only one item to be collapsed at the time, like:
![sidebar-autotoggle](https://user-images.githubusercontent.com/46919333/51524015-592d1880-1e2d-11e9-909c-f9e567cc9548.gif)

I done it by using my own function, but it would be nice to have native on/off prop option for this behaviour.

**Comment by yaminncco** [comment]
I will work on this thanks

**Comment by yaminncco** [comment]
added `showOneChild` prop in v3.4.0
