### ISSUE TITLE
Active menu is not working for child route using Inertia redirect

### ISSUE THREAD

**Issue by sivabhargavib** [yaminncco/vue-sidebar-menu#253]
I'm using Laravel 8 + inertia + vue 3
The active menu is not working for the nested links.

/users => I want to make it "active"
/users/1/edit ==> current

I tried the custom link in main.js. Its not working
import { createApp, h } from "vue";
const customLink = {
    name: 'CustomLink',
    props: ['item'],
    render() {
        return h('a', this.$slots.default())
    }
}

const app = createApp({});
app.component('custom-link', customLink)

**Comment by yaminncco** [comment]
This might help https://github.com/yaminncco/vue-sidebar-menu/issues/217#issuecomment-1030840475

**Comment by sivabhargavib** [comment]
> This might help [#217 (comment)](https://github.com/yaminncco/vue-sidebar-menu/issues/217#issuecomment-1030840475)

Thanks. its working
