### ISSUE TITLE
Menu groups

### ISSUE THREAD

**Issue by prattcmp** [yaminncco/vue-sidebar-menu#256]
It would be great if we could put spacing between menu items based on groupings.

See example:
<img width="223" alt="Screenshot 2023-05-02 at 1 17 03 PM" src="https://user-images.githubusercontent.com/1497950/235737948-2e29b32b-7e00-44e4-8c36-d1170df71672.png">

**Comment by yaminncco** [comment]
Possible with a component item

```
import { h } from 'vue'

// menu
{
  ...
  {
    component: h('div', { style: { height: '50px' }})
  }
  ...
}
```
