### ISSUE TITLE
Adding link to footer?

### ISSUE THREAD

**Issue by calicoder77** [yaminncco/vue-sidebar-menu#259]
Good day,

Just wondering if it is possible to access the footer like we do the header in:

```
const menu = [
    {
        header: 'Sidebar menu',
        hiddenOnCollapse: true,
    }
]
```

I'm trying to add an icon and link in there but not sure if that is supported?

Thanks again.

**Comment by yaminncco** [comment]
You can use footer slot

```
<sidebar-menu>
  <template #footer>footer</template>
</sidebar-menu>
```

**Comment by calicoder77** [comment]
> You can use footer slot
> 
> ```
> <sidebar-menu>
>   <template #footer>footer</template>
> </sidebar-menu>
> ```

Good morning @yaminncco, unfortunately I tried that and get an error of `v-slot directive must be owned by a custom element, but template is not. `

**Comment by yaminncco** [comment]
Can you show me how you're using the component

**Comment by calicoder77** [comment]
Works now, thanks @yaminncco. I had a self-closing tag `/>` on my previous `<sidebar-menu>` and adding the `<sidebar-menu>` allows the 1st tip you gave to work well.
