### ISSUE TITLE
responsive - break into hamburger

### ISSUE THREAD

**Issue by nikola-pavlovic** [yaminncco/vue-sidebar-menu#26]
Hi,
Could we have a prop --- `break_at` or something, for defining window width at which our sidebar will break into hamburger at the top of the screen.
Right now, colapsed sidebar doesn't look good at the most mobile phones...

This should be a **must-have** :)

**Comment by yaminncco** [comment]
if you want the sidebar to collapse on mobile you can use `collapsed` prop and update it on resize
```
<sidebar-menu :collapsed="collapsed" />

export default {
    data() {
        return {
            collapsed: window.innerWidth <= 960 ? true : false
        }
    },
    created() {
        window.addEventListener('resize', () => {
            if ( window.innerWidth <= 960 ) {
                this.collapsed = true
            } else if ( window.innerWidth > 960) {
                this.collapsed = false
            }
        });
    }
}
```

**Comment by nikola-pavlovic** [comment]
I ment something like this (for mobiles)...
![responsive-sidebar](https://user-images.githubusercontent.com/46919333/51558032-be5d2a00-1e7e-11e9-83cb-ac7f7e4182a2.gif)


...option to toggle side menu completely invisible - until hamburger icon touched (on the top of the page).

It is not a big deal to do this by ourselves, but it would be a nice option to have a **prop** defining at which window width sidemen will break into hamburger.

**Comment by yaminncco** [comment]
not adding this because it's better to do it outside of the component
