### ISSUE TITLE
change item hover color

### ISSUE THREAD

**Issue by okeowosv** [yaminncco/vue-sidebar-menu#262]
I would like to change the item hover color to blend with my brand, thanks

<img width="479" alt="Xnapper-2023-09-06-10 06 54 AM" src="https://github.com/yaminncco/vue-sidebar-menu/assets/51259940/1ecfb2b0-4c72-4a8d-969b-ebd67d10f91a">

**Comment by yaminncco** [comment]
With CSS:

```
.v-sidebar-menu .vsm--mobile-bg {
  background-color: red;
}
.v-sidebar-menu.vsm_collapsed .vsm--link_level-1.vsm--link_hover .vsm--icon {
  background-color: red;
}
```
