### ISSUE TITLE
Ability to use flyout menu item expander when menu is not collapsed

### ISSUE THREAD

**Issue by m-henson** [yaminncco/vue-sidebar-menu#274]
It would be helpful if there was an option to always use the flyout expander when a menu item with children is expanded. Like how it is being handled when the menu is collapsed, but when the menu is not collapsed as well.

Expanding to the side can be helpful if the menu is already taking up a lot of vertical space, or for child items to act more like a context menu.

Is this possible in the current version?

**Comment by yaminncco** [comment]
Sorry but not possible to implement without a major change
