### ISSUE TITLE
How can I keep only one child opened at a time for multiple levels dropdown

### ISSUE THREAD

**Issue by anhcunmio** [yaminncco/vue-sidebar-menu#275]
I see the showOneChild prop on the document but it works for the first level only.

Is there a way to close all siblings when clicking the sub-menu?

Thanks

**Comment by yaminncco** [comment]
Currently only the first level is supported

**Comment by yaminncco** [comment]
Added 'deep' support in v5.4.0.
```vue
<sidebar-menu :show-one-child="'deep'" />
```
