### ISSUE TITLE
Active Menu CSS

### ISSUE THREAD

**Issue by Seol827** [yaminncco/vue-sidebar-menu#278]
Hello there!
When I click a sub-item on the sidebar menu, I want to style the font of that item. (there's no href).
How can I change that?
ex) click the 'title1' => 'title1' text should be bold.

```
const menu = [
  // {
  //   header: 'Header',
  //   hiddenOnCollapse: true,
  // },
  {
    title: 'Dash Board',
    icon: 'ri-keyboard-box-line',
    href: '/',
    child: [
      {
        title: 'title1',
      },
      {
        title: 'title2',
      }
  }
]
```

**Comment by yaminncco** [comment]
You may consider using a [custom link](https://github.com/yaminncco/vue-sidebar-menu#customize-link) component then add the styles from there on click.
