### ISSUE TITLE
Evolution : add two more props

### ISSUE THREAD

**Issue by abonanni** [yaminncco/vue-sidebar-menu#28]
Hello,
I think it would be interesting to add the two following props : 

- collapse-btn-position (top or bottom) : choose if the button is hover or below the menu
- menu-position (left or right): draw the menu on the left or on the right in the page

**Comment by yaminncco** [comment]
menu position will be in the future but for the btn you can just use css

**Comment by yaminncco** [comment]
added `rtl` prop in v3.6.0
