### ISSUE TITLE
sass: "Deprecation Warning: The legacy JS API is deprecated and will be removed in Dart Sass 2.0.0."

### ISSUE THREAD

**Issue by rubjo** [yaminncco/vue-sidebar-menu#281]
<img width="716" alt="image" src="https://github.com/user-attachments/assets/a7cd63bb-de49-4620-b8a8-5a0ea533deb3">

https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

**Comment by yaminncco** [comment]
Fixed in v5.4.2
