### ISSUE TITLE
Sub menus not showing when collapsed

### ISSUE THREAD

**Issue by vpratfr** [yaminncco/vue-sidebar-menu#283]
Hi,

We have been using your component for a while, and recently upgraded our project to vue3/tailwind CSS.

I have it all setup except for the submenus that are not able to slide out when the bar is collapsed.

Any idea or advice regarding how to debug that? I cannot find a way to understand what the issue could be.

**Comment by yaminncco** [comment]
Maybe because of `disableHover` prop?
Can you provide a minimal reproduction?

**Comment by vpratfr** [comment]
Hi,

Found it yesterday.

The sidebar was inside a div and I guess the flyout menu was hidden by the div border. Strangely I had tried to modify the div to have overflow visible but that had not changed anything.

Moving the sidebar out of the div solved the issue.
