### ISSUE TITLE
Documentation on, or allowing, custom styles

### ISSUE THREAD

**Issue by djzara** [yaminncco/vue-sidebar-menu#3]
This is a fantastic little component for Vue and I'm extremely impressed by the functionality, and smoothness.

One thing I do need to ask, or optentially suggestion, is the ability to customize the styles in use so that we can do things like change the colors, fonts, size, etc, to better suit our app's theme. Sure, we can just look and see what styles are already in use and just override, but I think it would be much more appropratei to be able to provide some sort of object or array of styles and c lasses to allow for this sort of customization.

I went through the source code and found no such props, or documentation thereof, so I'm not sure what that'll do. If need be, and as I have time, I can see about a fork and PR to try and enabled this feature.

Otherwise, great work!! I don't see any labels, else I'd label this as not a bug, but a feature request.

**Comment by yaminncco** [comment]
Thanks for your suggestion. I will add more about customization in the future

**Comment by djzara** [comment]
Thanks so much! I'll fork anyway and see if I can help you out with a PR as time allows :)

Great work!!
