### ISSUE TITLE
Call a function instead of href on click

### ISSUE THREAD

**Issue by petersource2** [yaminncco/vue-sidebar-menu#30]
I'm new to Vue.js and I haven't been able to work out if this is possible with your sidebar menu. If this is not possible, could I make this a feature request?

Another thing I would like is the possibility to show multiple menu child items as selected, imagine selecting several child 'categories' and on click being able to show it as selected or not. If this is not something you are not interested in implementing I might consider forking. Your menu is amazing by the way. Very sleek!

**Comment by yaminncco** [comment]
I am working on the first, but for your second suggestion i can't implement it, I want to keep the component as a navigation

**Comment by yaminncco** [comment]
in v3.5.0 you can use the [`itemClick`](https://github.com/yaminncco/vue-sidebar-menu#events)
