### ISSUE TITLE
How to use it in the Nuxt.js?

### ISSUE THREAD

**Issue by Rajan** [yaminncco/vue-sidebar-menu#31]
I'm building an open-source CMS using Nuxt.js and would love to use this. =)

**Comment by yaminncco** [comment]
I don't have too much experience with nuxt, but you can follow their [doc ](https://nuxtjs.org/guide/plugins#vue-plugins)on how to use plugin

**Comment by Rajan** [comment]
Already fixed & committed yesterday. The code is in here:
https://github.com/lesspod/lesspod-2.0
