### ISSUE TITLE
Font Awesome Icons doesn't show upon building to Web Component

### ISSUE THREAD

**Issue by jippy89** [yaminncco/vue-sidebar-menu#33]
**Little background**  
I was trying to make a web component out of `vue-sidebar-menu` upon testing it works great!

![image](https://user-images.githubusercontent.com/33748953/53711812-79151a80-3e76-11e9-9d01-03b26b95cf8c.png)

However as soon as I try to build into a web component using
```
scripts: {
   "build-wc": "vue-cli-service build --target wc --name vue-sidebar src/App.vue"
}
```
This happens

![try-vue-sidebar-menu](https://user-images.githubusercontent.com/33748953/53712938-8da7e180-3e7b-11e9-979a-3c53b7b7fb5a.png)

The right black screen is intentional. And it seems that the fontawesome icons disappear, I was confused because other icons such as arrow, and the sidebar button, didn't disappear as well. 

**The Problem:**
Font Awesome disappear upon building as a web component.

**What I want**
Work like in the dev mode,

**Notes:**  
I was using Vue CLI 3.4.0
And here's my current App.vue
```
<template>
    <div>
        <v-sidebar 
            :menu="menu" 
            :collapsed="collapse"
            :height="window.height + 'px'"
            width="254px"></v-sidebar>
        <div id="overlay" @click="collapse = !collapse"></div>
    </div>
</template>

<script>
    import { SidebarMenu } from 'vue-sidebar-menu'
    import WindowSize from '@/mixins/WindowSize.js'
    import 'vue-sidebar-menu/dist/vue-sidebar-menu.css'

    export default {
        mixins: [WindowSize],
        components: {
            "v-sidebar": SidebarMenu
        },
        data(){
            return {
                collapse: true,
                menu: [
                    {
                        header: true,
                        title: 'Testing!~',
                        // component: componentName
                        // visibleOnCollapse: true
                    },
                    {
                        href: '/',
                        title: 'Dashboard',
                        icon: ['fa fa-user'],
                        /*
                        disabled: true
                        badge: {
                            text: 'new',
                            // class:''
                        }
                        */
                    },
                    {
                        title: 'Charts',
                        icon: ['fa fa-chart-area'],
                        child: [
                            {
                                href: '/charts/sublink',
                                title: 'Sub Link',
                            }
                        ]
                    },
                    {
                        title: "Testing",
                        icon: 'fa fa-coffee'
                    }
                ],
            }
        },
    }
</script>
```

**Comment by yaminncco** [comment]
Hi, I don't know enough about wc, but it looks like you need to re-import font awesome in the component too

**Comment by jippy89** [comment]
Hm.. yeah, I just read it lately.. I know, but what I wondered was how did the `<->` and dropdown icons didn't break, while other icons in top (for menu especially) has lost its icon.  I thought maybe if you know, or figure it out maybe it'll just need a little tweak.

But I guess I have to dig into the source code if I really wanted to use it as a web component :/
Permission to fork? I'll try to make it when I'm free.

Thanks for replying! ;D
