### ISSUE TITLE
I would like to hide a menu item 

### ISSUE THREAD

**Issue by SpoturDeal** [yaminncco/vue-sidebar-menu#34]
Hello,

Thanks for this great sidebar menu.

I would like to hide a menu item for a user that is not authorized in. 
disable is possible, but i do not want unauthorized users to the the menu item/option

Now i have added a onLog to each item i added a computed value to filter the ones needed for my meny

```
data() {
    return {
      items: [
        {
          header: true,
          title: 'Navigatie',
          onLog: false
        },
        {
          href: '/',
          title: 'Dashboard',
          icon: 'fa fa-home',
          onLog: true
        },
       ......

computed: {
    menu() {
      return this.items.filter(mAuth => mAuth.onLog === true)
    }
  },

    ...

```

Is it possible to integrate some into your code
Many thanks in advance

**Comment by yaminncco** [comment]
Hi, I don't see the need for an option to hide items, your solution is enough

**Comment by DrCord** [comment]
this doesn't work as the computer property is not available to use on init...
