### ISSUE TITLE
How to use OnItemClick ?

### ISSUE THREAD

**Issue by thibaultchazal** [yaminncco/vue-sidebar-menu#35]
I'd like to add actions on click but I can't figure how to do it...

I added @itemClick="onItemClick" to the sidebar and onItemClick in the methods but it is not recognize.

Did I do something wrong ?

`    <sidebar-menu id="AdminNav" @itemClick="onItemClick" :class="{'collapsed' : collapsed}" :menu="menu" :collapsed="collapsed" @collapse="onCollapse" :theme="selectedTheme" />
`
And 
`methods: {
    onItemClick(event, item) {
        console.log('Item Clicked')
        this.$store.dispatch('setClient', null)
        this.$store.dispatch('setToken', null)
        this.$store.dispatch('setAdmin', null)
        this.$store.dispatch('setUser', null)
          .then(() => this.$router.push('/login'))
    },`

**Comment by yaminncco** [comment]
What do you mean by not recognize? @itemClick is available from v3.5.0 make sure to update

**Comment by thibaultchazal** [comment]
Okay, I was using an older version. I just updated but still, when I click on any item, I am redirected to the right path but what's inside my onItemClick function is not processed.

I've added a console.log to be sure and it's never printed.

Do I use it wrong ?

**Comment by yaminncco** [comment]
not sure why is not working for you, can you make a reproduction

**Comment by thibaultchazal** [comment]
Here is the whole code of my component

```javascript
<template>
    <sidebar-menu id="AdminNav" @itemClick="onItemClick" :class="{'collapsed' : collapsed}" :menu="menu" :collapsed="collapsed" @collapse="onCollapse" :theme="selectedTheme" />
</template>

<script>
import { SidebarMenu } from 'vue-sidebar-menu'
import '@fortawesome/fontawesome-free/css/all.css'
import 'vue-sidebar-menu/dist/vue-sidebar-menu.css'

export default {
  name: 'adminNav',
  components: {
    SidebarMenu
  },
  data () {
    return {
      menu: [
        // {
        //   header: false,
        //   title: 'Menu Admin'
        // },
        {
          href: '/admin',
          title: 'Talk It Easy',
          icon: 'fab fa-pied-piper-hat'
        },
        {
          href: '/adminclients',
          title: 'Gestion des clients',
          icon: 'fas fa-users'
        },
        {
          href: '/admincoachs',
          title: 'Gestion des Coachs',
          icon: 'fas fa-user-astronaut'
        },
        {
          title: 'Gestion des circuits',
          icon: 'fas fa-route',
          child: [
                    {
                        href: '/admincourse/1',
                        title: 'Niveau 1',
                    },
                    {
                        href: '/admincourse/2',
                        title: 'Niveau 2',
                    },
                    {
                        href: '/admincourse/3',
                        title: 'Niveau 3',
                    },
                ]
        },
        {
          href: '/adminmedias',
          title: 'Gestion des médias',
          icon: 'fas fa-film'
        },
        {
          href: '/administration',
          title: 'Administration',
          icon: 'fas fa-gopuram'
        },
        {
          href: '/admin',
          title: 'Deconnexion',
          icon: 'fas fa-sign-out-alt'
        }
      ],
      collapsed: true,
      showChild: true,
      theme: ['', 'white-theme'],
      selectedTheme: 'white-theme'
    }
  },
  methods: {
    onItemClick(event, item) {
      console.log('Item Clicked')
        this.$store.dispatch('setClient', null)
        this.$store.dispatch('setToken', null)
        this.$store.dispatch('setAdmin', null)
        this.$store.dispatch('setUser', null)
    },
    onCollapse (val) {
      console.log(`collapsed ${val}`)
      this.collapsed = val
    }
  }
}
</script>```

**Comment by yaminncco** [comment]
your code work fine for me, are you using vue-router?

**Comment by thibaultchazal** [comment]
Yes I am, in History mode

```Javascript
...
Vue.use(Router)

let router = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'home',
      component: Home
    },
...
```

**Comment by yaminncco** [comment]
hmm, i realy dont know why is not working for you

**Comment by thibaultchazal** [comment]
In fact, it's working in production mode but not in development. I'll let you know once I found why.

**Comment by thibaultchazal** [comment]
Hi @yaminncco,
Just find a solution (and a clue of the problem).

If I remove the href, the itemClick event is fired and call the method.
I think the problem was the item was redirecting the user to the href before the method is called.

````
{
// href: '/login',
  title: 'Deconnexion',
  icon: 'fas fa-sign-out-alt'
}
````

**Comment by Guerriero81** [comment]
Can i have possibility to show how item I clicked?

**Comment by ardasatata** [comment]
I'm using it with nuxt, seems fine to me
