### ISSUE TITLE
Need an example of how to use this with Vue router

### ISSUE THREAD

**Issue by paulsimongb** [yaminncco/vue-sidebar-menu#36]

**Comment by yaminncco** [comment]
the demo is already an example of how to use with vue-router, not sure if i need to add more info to the doc

**Comment by paulsimongb** [comment]
Unless there is something I have missed the demo just says use <router-link> instead of <a> but the example actually shows href so I am not sure what the equivalent of that is for the router?

**Comment by yaminncco** [comment]
I meant to say that you can check [demo ](https://github.com/yaminncco/vue-sidebar-menu/tree/master/demo)to see how vue-router is used, you need to sync menu `href` with vue-router `path`

```
...
// vue-router routes
routes: [
    {
        path: '/',
        name: 'Installation',
        component: Installation
    },
    {
        path: '/basic-usage',
        name: 'BasicUsage',
        component: BasicUsage
    },
    {
        path: '/props',
        name: 'Props',
        component: Props
    },
    {
        path: '/events',
        name: 'Events',
        component: Events
    },
    {
        path: '/styling',
        name: 'Styling',
        component: Styling
    }
]
...
```

```
...
// vue-sidebar-menu menu
menu: [
    {
        href: '/',
        title: 'Installation',
        icon: 'fa fa-download'
    },
    {
        href: '/basic-usage',
        title: 'Basic Usage',
        icon: 'fa fa-code'
    },
    {
        href: '/props',
        title: 'Props',
        icon: 'fa fa-cogs'
    },
    {
        href: '/events',
        title: 'Events',
        icon: 'fa fa-bell'
    },
    {
        href: '/styling',
        title: 'Styling',
        icon: 'fa fa-palette'
    }
]
...
```

**Comment by paulsimongb** [comment]
Hi Many thanks for your quick reply. I got the basic routing working. However, the stumbling block is that we use OKTA for authentication. That uses a special route /implicit/callback. I tried adding this as a href but it didn't work

In the component I originally used for side bar navigation I have
`<ul>
            <router-link :to="{name:'Home'}" tag="button" id='home-button'>Home</router-link> 
            <br><br>
            <router-link :to="{name:'CreateCode'}" tag="button" id='create-button'>Create</router-link>
            <br><br>
            <button v-if='authenticated' v-on:click='logout' id='logout-button'> Logout </button>  
            <button v-else v-on:click='login' id='login-button'> Login </button>
        </ul>`

The last bit displays a login or logout button depending on whether the user has authenticated yet.

The top of my routes looks like this 

`routes: [
  
    {  
      path: '/implicit/callback',
      component: Auth.handleCallback()
    },
    {  
      path: '/',
      name: 'Home',
      component: Home,`
},
    {
      path: '/CreateCode',
      name: 'CreateCode',
      component: CreateCode,
      meta: {
        requiresAuth: true
      }
    },

Is there a way to do something similar using sidebar?

Apologies if I am asking something basic. I have been developing for years, but in Vue for only a matter of weeks.

Regards

Paul Simon

**Comment by paulsimongb** [comment]
Hi Many thanks for your quick reply. I got the basic routing working. However, the stumbling block is that we use OKTA for authentication. That uses a special route /implicit/callback. I tried adding this as a href but it didn't work

In the component I originally used for side bar navigation I have
<ul> <router-link :to="{name:'Home'}" tag="button" id='home-button'>Home</router-link> <br><br> <router-link :to="{name:'CreateCode'}" tag="button" id='create-button'>Create</router-link> <br><br> <button v-if='authenticated' v-on:click='logout' id='logout-button'> Logout </button> <button v-else v-on:click='login' id='login-button'> Login </button> </ul>

The last bit displays a login or logout button depending on whether the user has authenticated yet.

The top of my routes looks like this

`routes: [

{  
  path: '/implicit/callback',
  component: Auth.handleCallback()
},
{  
  path: '/',
  name: 'Home',
  component: Home,`
},
{
path: '/CreateCode',
name: 'CreateCode',
component: CreateCode,
meta: {
requiresAuth: true
}
},

Is there a way to do something similar using sidebar?

Apologies if I am asking something basic. I have been developing for years, but in Vue for only a matter of weeks.

Regards

Paul Simon

**Comment by paulsimongb** [comment]
Sorry re-posting as the code markup doesn't seem to have done what I expected

Hi Many thanks for your quick reply. I got the basic routing working. However, the stumbling block is that we use OKTA for authentication. That uses a special route /implicit/callback. I tried adding this as a href but it didn't work

In the component I originally used for side bar navigation I have

<ul>
            <router-link :to="{name:'Home'}" tag="button" id='home-button'>Home</router-link> 
            <br><br>
            <router-link :to="{name:'CreateCode'}" tag="button" id='create-button'>Create</router-link>
            <br><br>
            <button v-if='authenticated' v-on:click='logout' id='logout-button'> Logout </button>  
            <button v-else v-on:click='login' id='login-button'> Login </button>

The last bit displays a login or logout button depending on whether the user has authenticated yet.

The top of my routes looks like this

routes: [
  
    {  
      path: '/implicit/callback',
      component: Auth.handleCallback()
    },
    {  
      path: '/',
      name: 'Home',
      component: Home,
    },
    {
      path: '/CreateCode',
      name: 'CreateCode',
      component: CreateCode,
      meta: {
        requiresAuth: true
      }
    },


Is there a way to do something similar using sidebar?

Apologies if I am asking something basic. I have been developing for years, but in Vue for only a matter of weeks.

Regards

Paul Simon

**Comment by paulsimongb** [comment]
Sorry re-posting as the code markup doesn't seem to have done what I expected

Hi Many thanks for your quick reply. I got the basic routing working. However, the stumbling block is that we use OKTA for authentication. That uses a special route /implicit/callback. I tried adding this as a href but it didn't work

In the component I originally used for side bar navigation I have

`
            <router-link :to="{name:'Home'}" tag="button" id='home-button'>Home</router-link> 
            <br><br>
            <router-link :to="{name:'CreateCode'}" tag="button" id='create-button'>Create</router-link>
            <br><br>
            <button v-if='authenticated' v-on:click='logout' id='logout-button'> Logout </button>  
            <button v-else v-on:click='login' id='login-button'> Login </button>
`
The last bit displays a login or logout button depending on whether the user has authenticated yet.

The top of my routes looks like this

routes: [

{  
  path: '/implicit/callback',
  component: Auth.handleCallback()
},
{  
  path: '/',
  name: 'Home',
  component: Home,
},
{
  path: '/CreateCode',
  name: 'CreateCode',
  component: CreateCode,
  meta: {
    requiresAuth: true
  }
},
Is there a way to do something similar using sidebar?

Apologies if I am asking something basic. I have been developing for years, but in Vue for only a matter of weeks.

Regards

Paul Simon

**Comment by paulsimongb** [comment]
Hi Many thanks for your quick reply. I got the basic routing working. However, the stumbling block is that we use OKTA for authentication. That uses a special route /implicit/callback. I tried adding this as a href but it didn't work

In the component I originally used for side bar navigation I have

`            <router-link :to="{name:'Home'}" tag="button" id='home-button'>Home</router-link> `
 `           <br><br>`
 `           <router-link :to="{name:'CreateCode'}" tag="button" id='create-button'>Create</router-link>`
 `           <br><br>`
 `           <button v-if='authenticated' v-on:click='logout' id='logout-button'> Logout </button>  `
  `          <button v-else v-on:click='login' id='login-button'> Login </button>`

The top of my routes looks like this

`routes: [
  
    {  
      path: '/implicit/callback',
      component: Auth.handleCallback()
    },
    {  
      path: '/',
      name: 'Home',
      component: Home,
    },
    {
      path: '/HellowWorld',
      name: 'HelloWorld',
      component: HelloWorld,
    },
    {
      path: '/CreateCode',
      name: 'CreateCode',
      component: CreateCode,
      meta: {
        requiresAuth: true
      }
    },
`

Is there a way to do something similar using sidebar?

Apologies if I am asking something basic. I have been developing for years, but in Vue for only a matter of weeks.

Regards

Paul Simon`

**Comment by yaminncco** [comment]
What's the issue here? I created a new project with OKTA and it worked fine

**Comment by paulsimongb** [comment]
Sorry for the delay in replying. Other priorities came up, so I have not have another chance to look at Sidebar.

Presumably, if you got it to work you created custom login and logout components, rather than relying on the built in OKTA dialogs?

Anyway, I will close this issue. I will probably stick with my home grown Nav Bar for now.
