### ISSUE TITLE
Server side rendering - window is not defined

### ISSUE THREAD

**Issue by codetrove-development** [yaminncco/vue-sidebar-menu#38]
Hi, I am getting window is not defined in the dist build. It's the module wrapper code not your library so I think a change in the webpack config would fix this.

function(t,e){"object"==typeof exports&&"object"==typeof module?module.exports=e():"function"==typeof define&&define.amd?define([],e):"object"==typeof exports?exports["vue-sidebar-menu"]=e():t["vue-sidebar-menu"]=e()}(window,function()

**Comment by codetrove-development** [comment]
I've found a workaround as just doing:

  import VueSidebarMenu from 'vue-sidebar-menu/src/index'

Awesome library btw! :)

**Comment by yaminncco** [comment]
ssr is not supported
