### ISSUE TITLE
Menu bar overlapping with Bootstrap vue

### ISSUE THREAD

**Issue by FreddyCrugger** [yaminncco/vue-sidebar-menu#40]
Hello,

The menu is really great, just a small problem, no idea if you could add a z-index update in your css but when you use the dev tool from chrome and set the layout to mobile and click on your menu bar while using bootstrap vue, the menu bar appears behind the bootstrap4 layout causing the scroll bar to be difficult to close.

Please see this:
`https://www.screencast.com/t/TiPx76DwIFK`

I can click on the navbar on its left side but not on the right due to z-index.

Thanks for the great work.

**Comment by yaminncco** [comment]
adding z-index should fix this issue, I will update it thanks

**Comment by FreddyCrugger** [comment]
Thank you so much! :-)

**Comment by FreddyCrugger** [comment]
Just to let you know, your update worked :-)

Thank you!
