### ISSUE TITLE
PROPS NOT WORKING

### ISSUE THREAD

**Issue by ruslanzelinskyy** [yaminncco/vue-sidebar-menu#41]
Props are not working properly (width, widthCollapsed). Provide an example how to use it or fix error please. Thanks!

**Comment by yaminncco** [comment]
can you share your code on how you are passing props?

**Comment by ruslanzelinskyy** [comment]
`<template>
    <aside>
        <SidebarMenu
                :menu="menu"
                :collapsed="collapsed"
                :width="width"
                :widthCollapsed="widthCollapsed"
        >
        </SidebarMenu>
    </aside>
</template>

<script>
import { SidebarMenu } from 'vue-sidebar-menu'
import 'vue-sidebar-menu/dist/vue-sidebar-menu.css'
export default {
    name: 'Aside',
    components: { SidebarMenu },
    data: function () {
        return {
            menu: [
                {
                    href: '/',
                    title: 'Site',
                    icon: 'fa fa-step-backward'
                }
            ],
            collapsed: false,
            width: {
                type: String,
                default: '350px'
            },
            widthCollapsed: {
                type: String,
                default: '50px'
            },
        }
    }
}
</script>`

**Comment by yaminncco** [comment]
width & widthCollapsed need a string value

```
data() {
    return {
        width: '350px'
        widthCollapsed: '50px'
    }
}
```

**Comment by ruslanzelinskyy** [comment]
Ou.. i get it :)
All is working perfectly. Thanks!
