### ISSUE TITLE
Remember state

### ISSUE THREAD

**Issue by xuanzhan12** [yaminncco/vue-sidebar-menu#42]
One feature that'd be nice to have is remembering which children were open on refreshing the page. Is there currently a way to do this with Vuex?

**Comment by yaminncco** [comment]
only the child that match route will stay open, sorry cant add this

**Comment by xuanzhan12** [comment]
Fair enough, thanks. I'm actually having a problem with that, where the "active-item" class gets assigned correctly and everything, but the children aren't automatically shown. I think the problem's somewhere else in my Vue config though. I'll update when I find out what it is.

**Comment by MrDuFei** [comment]
Hey, xuanzhan12! have you solved this problem?

**Comment by xuanzhan12** [comment]
Hi, if you mean the children not being shown automatically, sorry I think the problem disappeared eventually but I can't remember what the cause was. I know this isn't very helpful :(
If you mean remembering which children are kept open on refresh, I gave up on that idea.
