### ISSUE TITLE
Get/Set menu data from database

### ISSUE THREAD

**Issue by darklord1990** [yaminncco/vue-sidebar-menu#44]
Hi 

Do you have any option to get menu data from database ?
Especially for the sub menu.

Thanks
Mark

**Comment by yaminncco** [comment]
sorry there is no option for this at the moment. maybe you can use itemClick event then push child to the item when loaded

**Comment by darklord1990** [comment]
I used $set function to add "child" to main menu
`this.$set(tmp[i], 'child', response.data);`
