### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by discontinuos** [yaminncco/vue-sidebar-menu#45]
It would be nice if 'badge' could have a Tooltip (mapped to html title attribute) and a Icon attributes (same behaviour as icon for subitems). I think it's little amout of code, and using the class attribute to produce same result painful. Thanks a lot, Pablo.

use cases: adding a warning icon with a title to same items that neet attention.

**Comment by yaminncco** [comment]
if I understand correctly, you want to add title attribute to badge? i will think about this.

**Comment by discontinuos** [comment]
Yes, it would be the 'title' attribute (i called it tooltip, but actually i
imaged implemented as an html title attribute) and an Icon, to be able to
put an icon instead or next to the current text value...

**Comment by yaminncco** [comment]
add icon through class property or you can use pseudo-element

**Comment by discontinuos** [comment]
I know i could do that.

I just thought that as components are made for code readability and
encapsulatoin of techy things, indicating a material vue icon tag wouble be
nice.... But of it's your call...

Regards, Pablo.

**Comment by yaminncco** [comment]
in 3.7.0 you can add attributes

```
badge: {
    attributes: {
        title: 'your title'
    }
}
```

**Comment by discontinuos** [comment]
thanks!
