### ISSUE TITLE
Will be possible to set an image either title text in the header

### ISSUE THREAD

**Issue by darkman97i** [yaminncco/vue-sidebar-menu#46]
I'm thinking in something like can be shown here https://adminlte.io/themes/AdminLTE/index2.html

**Comment by yaminncco** [comment]
you can add a component that contain img to the header

```
...
    menu [
        {
            header: true,
            component: yourComponent
        }
    ]
...
```

**Comment by darkman97i** [comment]
I was obfuscated in passing HTML and I have not considered the component option. Thanks, it works perfectly.

**Comment by 8secz-johndpope** [comment]
this needs to be in main demo
life saver - thanks

**Comment by darkman97i** [comment]
If you want to test, I have a vue component:
header.vue
```
<template>
  <div class="headerIcon">
    <img src="images/icon.png" alt="icon description "/>
  </div>
</template>

<style scoped>
  .headerIcon {
    padding-top: 11px;
    padding-left: 15px;
    padding-bottom: 60px;
  }
</style>
```

Then in the menu options:
menu [
        {
            header: true,
            component: header
            ....
        }
    ]
