### ISSUE TITLE
Submenu isn't created, possibly "Source Map error"

### ISSUE THREAD

**Issue by Djusa** [yaminncco/vue-sidebar-menu#48]
I added this plugin to Laravel installation, I can open/close the whole menu but I cannot open/see submenu items. There is the arrow icon but it doesn't work.
In the console I can see the warning message:

> Source map error: request failed with status 404
> Resource URL: http://127.1.1.1:8088/js/app.js
> Source Map URL: vue-sidebar-menu.js.map

**Comment by yaminncco** [comment]
can you show your code

**Comment by yaminncco** [comment]
closing since there was no response
