### ISSUE TITLE
alias support

### ISSUE THREAD

**Issue by discontinuos** [yaminncco/vue-sidebar-menu#51]
Hi,
I have a router item which has aliases (used for tabs). Eg. /mypage/tab1, mypage/tab2.

At router definition I have:
	path: 'mypage',
	alias: ['mypage/tab1', 'mypage/tab2']

Everything goes ok, except that sidebarmenu does not accept alias for href definitions, so the selected item does not hightlight when alias are routed. 

I would need to be able to do:

	var item = {
						href: 'mypage',
						alias: ['mypage/tab1', 'mypage/tab2'],
						};

And have all checked for selected menuitem....

Would that be possible?

**Comment by discontinuos** [comment]
Hi. It's really little code. I tested and works ok changing isLinkActive at mixing...

It would be nice to have it officially =)

Thanks, Pablo.


    isLinkActive (item) {
      if (this.$route) {
        return this.matchRoute(item, this.$route.path + this.$route.hash)
      } else {
        return this.matchRoute(item, window.location.pathname + window.location.hash)
      }
    },
    matchRoute(item, route) {
	if (item.href === route) {
		return true
	}
	if (item.alias) {
		if (Array.isArray(item.alias)) {
			for(let i = 0; i < item.alias.length; i++) {
				if (item.alias[i] === route) return true	
			}
		} else {
			return (item.alias === route)	
		}
	}
	return false
    },

**Comment by yaminncco** [comment]
hi, i will look into this thanks

**Comment by yaminncco** [comment]
added in v3.8.0

**Comment by clearideas** [comment]
Would be great to use regular expression and String.match rather than triple equals === operator.  Would allow for wildcards in alias field.   

with path-to-regexp dependancy (used by vue-router for regexp conversion for path notation conversion):

`import pathToRegexp from "path-to-regexp"
`
...
```
if (Array.isArray(item.alias)) {
		for(let i = 0; i < item.alias.length; i++) {
			if (RegExp(pathToRegexp(item.alias[i])).test(route)) return true	
		}
	} else {
		return (RegExp(pathToRegexp(item.alias)).test(route))	
	}
```
without dependancy:

```
if (Array.isArray(item.alias)) {
		for(let i = 0; i < item.alias.length; i++) {
			if (RegExp(item.alias[i]).test(route)) return true	
		}
	} else {
		return (RegExp(item.alias).test(route))	
	}
```

**Comment by yaminncco** [comment]
@clearideas regexp support will be implemented in the future thanks.
