### ISSUE TITLE
Regarding support for vue-font-awsome

### ISSUE THREAD

**Issue by hjelperne** [yaminncco/vue-sidebar-menu#52]
Hi,

Would it be possible to somehow add support for vue-fontawesome - so one can benefit from not including the enitre font-awsome library in all.css - as suggested above - but rather select which icons to bundle as the vue-font-awsome supports (as described by @thibaultchazal).

_Originally posted by @hjelperne in https://github.com/yaminncco/vue-sidebar-menu/issues/20#issuecomment-494793036_

**Comment by yaminncco** [comment]
hi i will add more options for the icons, thanks.

**Comment by gorkamolero** [comment]
Also very interested in custom icon components! Please post here when available.

**Comment by yaminncco** [comment]
added in v3.9.0, example to use with vue-fontawesome after you register icon component:

```
{
    href: '/',
    title: 'Dashboard',
    icon: {
        element: 'font-awesome-icon',
        attributes: {
            icon: 'coffee'
        }
    }
}
```

**Comment by hjelperne** [comment]
Hi,
Thanks for fixing this. Great!
I have now updated to use the vue-fontawesome icons instead, but I am experiencing the icons being much larger now - than previously (see attached image).
![image](https://user-images.githubusercontent.com/342842/60709492-d7c7cf00-9f10-11e9-98b7-fde6a7189ac8.png)

Code ref:
`                    {
                        href: '/',
                        title: 'CRM',
                        icon:  {
                            element: 'font-awesome-icon',
                            attributes: {
                                icon: 'medal',
                            }
                        },
                        disabled: true
                    },

                    {
                        href: '/',
                        title: 'CRM',
                        icon: 'fas fa-medal',
                        disabled: true
                    },`

Is the any way to control the sizing? 
Ref: https://github.com/FortAwesome/vue-fontawesome#user-content-basic

It would be really nice to have the icons smaller (like before ~ when using font-awsome directly).

Great work!

**Comment by hjelperne** [comment]
By the way - currently I use the following scss override to acheive smaller icons (like before):

`.v-sidebar-menu .vsm-item.first-item>.vsm-link>.vsm-icon {
        height: 16px !important; /* override height */
        margin-top: 6px; /* acheive correct vertical alignment */
    }`

**Comment by hjelperne** [comment]
And finally I noticed one more issue with switching to vue-fontawsome icons. 
The 2 expand icons for respectively: 
1) "submenus expand/collapse" icon (vsm-arrow) 
2) collpase menu icon (content: '\F337'; on button) 
become "squares" as they are no longer found when I remove the: 
**import '@fortawesome/fontawesome-free/css/all.css'**
which is basically the entire point of using vue-fontawsome instead.. (more compact).

Hope you can help.

Thanks.
Best regards,
H

**Comment by pablo-ernesto** [comment]
Could someone please provide how to import and/or use vue-awesome icons exactly? Because I tried a lot, but still no icons displayed.
What is missing/wrong in the code below?
Thanks in advance!
Best Regards

`
<template>
<sidebar-menu ref="sidebar"
            :menu="menuData"
            :collapsed="true"
            @item-click="onSidebarMenuItemClick"/>
...
</template>

<script>
import 'vue-awesome/icons'
import { SidebarMenu } from 'vue-sidebar-menu'
import 'vue-sidebar-menu/dist/vue-sidebar-menu.css'

export default {
    components: {
        SidebarMenu,
    },
    data: function () {
        return {
            menuData: [
                {
                    header: true,
                    title: 'Main Navigation',
                    hiddenOnCollapse: true,
                },
                {
                    title: 'Navigation item 1',
                    href: '/nav/item1',
                    icon: {
                        element: 'font-awesome-icon',
                        attributes: { 
                            icon: 'fas fa-check-double'
                        }
                    },
                },

`

**Comment by yaminncco** [comment]
@pablo-ernesto 

```
icon: {
    element: 'font-awesome-icon',
    attributes: { 
        icon: 'check-double'
    }
}
```

**Comment by mikecbone** [comment]
> And finally I noticed one more issue with switching to vue-fontawsome icons.
> The 2 expand icons for respectively:
> 
> 1. "submenus expand/collapse" icon (vsm-arrow)
> 2. collpase menu icon (content: '\F337'; on button)
>    become "squares" as they are no longer found when I remove the:
>    **import '@fortawesome/fontawesome-free/css/all.css'**
>    which is basically the entire point of using vue-fontawsome instead.. (more compact).
> 
> Hope you can help.
> 
> Thanks.
> Best regards,
> H

These points are still relevant for using vue-fontawesome with vue-sidebar-menu

**Comment by yaminncco** [comment]
@mikecbone you can use [slots](https://github.com/yaminncco/vue-sidebar-menu#slots)
