### ISSUE TITLE
How to use it with navbar?

### ISSUE THREAD

**Issue by Sogl** [yaminncco/vue-sidebar-menu#53]
Hello!
I use Bulma css-framework and Buefy UI components.
Unfortunately, there are no menu/sidebar component in Bulma and I decided to use yours.

I want to style it like this:
https://coreui.io/vue/demo/#/dashboard

But what I see after installation:
![image](https://user-images.githubusercontent.com/7556290/58819186-57bff800-8638-11e9-9fe0-bb23d182f76f.png)

Do I need to style it manually using css?
I'm also interested in off-canvas and main content movings.  

Any help is appreciated

**Comment by yaminncco** [comment]
yeah you need to use css same for off-canvas

**Comment by glevco** [comment]
Any plans on adding support to containers? That is, using the sidebar inside a specific element instead of assuming the whole viewport as the container

**Comment by yaminncco** [comment]
you can put the sidebar wherever you want and with css override position and height.
closing this issue

**Comment by glevco** [comment]
I tried to but it doesn't work, since "vh" units are used when calculating the hover elements position (when the sidebar is collapsed), for example.

**Comment by yaminncco** [comment]
I understand your issue now, I will work on this thanks

**Comment by Sogl** [comment]
Yeah it would be cool to have any template to simple include it to own project. I mean css transforms and transitions, responsive effects etc.

**Comment by yaminncco** [comment]
@glevco can you try the new version and see if fix your issue.

@Sogl i prefer to keep style customization through css.
