### ISSUE TITLE
Add support for other icon libraries

### ISSUE THREAD

**Issue by joeleoli** [yaminncco/vue-sidebar-menu#55]
With font-awesome, an icon is rendered using attributes
`<i class="fas fa-face"></i>`

With other icon libraries, like [material.io](material.io), the icon id is provided within the element's body instead of providing the icon id through attributes
`<span class="material-icons">face</i>`

**Comment by joeleoli** [comment]
#56 solves this issue

**Comment by yaminncco** [comment]
added in v3.10.0
