### ISSUE TITLE
Menu toggle icon not showing

### ISSUE THREAD

**Issue by nzediegwu1** [yaminncco/vue-sidebar-menu#57]
Thanks a lot for this awesome widget!
1. The toggle icon for opening/closing the sidebar does not show unlike can be seen in the demo. Could it be from later versions or I am not getting something right.
2. The toggle icon for opening/closing parent menu items also does not show

Would appreciate some help on this. Thanks!
Image attached below:

<img width="276" alt="Screen Shot 2019-06-24 at 7 42 36 PM" src="https://user-images.githubusercontent.com/29695968/60043611-6427f580-96b8-11e9-9280-dc8f0f0340b4.png">

**Comment by yaminncco** [comment]
if your not using Font Awesome 5 Free override css

```
.v-sidebar-menu .vsm-arrow:after {
    content: '\f105';
    font-family: 'Font Awesome 5 Free';
}

.v-sidebar-menu .collapse-btn:after {
    content: '\f337';
    font-family: 'Font Awesome 5 Free';
}
```

**Comment by nzediegwu1** [comment]
I'm using Font Awesome 4.7.0

**Comment by JelledFro** [comment]
I have the same problem. Also using Font Awesome 4.7. 
I tried 

`
.v-sidebar-menu .vsm-arrow:after {
  content: "\f105";
  font-family: "FontAwesome";
}
`
but that's not working either. And I'm unable to change the color of the button with 

`.v-sidebar-menu .collapse-btn {
  background-color: #ffffff !important;
}`

**Comment by yaminncco** [comment]
add class to the component ex sidebar then override css with

```
.sidebar.v-sidebar-menu .vsm-arrow:after {
  content: '\f105';
  font-family: 'FontAwesome';
}

.sidebar.v-sidebar-menu .collapse-btn:after {
  content: '\f07e';
  font-family: 'FontAwesome';
}
```

**Comment by JelledFro** [comment]
Still not working. I'm importing 4.7 in index.html like this
```
 <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
  />
```
And I can use all the icon classes elsewhere. Do I need to do anything else for it to work?

**Comment by yaminncco** [comment]
inspect element and check if styles are begin applied

**Comment by yaminncco** [comment]
in v3.11 you can customize icons using [slots ](https://github.com/yaminncco/vue-sidebar-menu#customize-icons )
