### ISSUE TITLE
@item-click does not work when menu is collapsed

### ISSUE THREAD

**Issue by nzediegwu1** [yaminncco/vue-sidebar-menu#58]
When the menu is collapsed, the item click method doesn't fire when I click on the `hoverable` menu item unlike it does when I open the menu and click the item directly
<img width="183" alt="Screen Shot 2019-06-24 at 8 44 40 PM" src="https://user-images.githubusercontent.com/29695968/60047251-2b404e80-96c1-11e9-9f40-7b485055d7f3.png">

**Comment by yaminncco** [comment]
can you provide a reproduction
