### ISSUE TITLE
Documentation on creating sub items

### ISSUE THREAD

**Issue by tomjdickson** [yaminncco/vue-sidebar-menu#6]
Documentation is missing on how to create sub-items.

Can't work out how to do it myself.
This is what I have tried: 

        {
            href: '/loggedin/dashboard',
            title: 'Documents',
            icon: 'fa fa-file',
            item : [
                {
                    href: 'nps',
                    title: 'New Product Submission',
                    icon: 'fa fa-file'
                }
            ]
        }

**Comment by yaminncco** [comment]
Fixed thanks.
