### ISSUE TITLE
showChild prop doesn't update as expected.

### ISSUE THREAD

**Issue by wehanvandermerwe** [yaminncco/vue-sidebar-menu#63]
Hello.

Firstly well done on a very nice component.

*** Key Points about my menu data:

1. I have a search bar on the menu in which I search through the menu.
2. I have menu data that I populate from my database via computed property.
3. I have the prop showChild set to false initially so the user can expand his/her menu manually.
4. I have a watcher on my search bar input value, which sets the searchVal data property which then triggers the computed property.

*** What I want to achieve:
When the user starts typing in the search field the menu should expand automatically and only show the value that he/she searched for.

*** To achieve this I did the following:
I set the prop showChild = true when the user starts typing in the search field, which means the menu item should collapse automatically, however, when the menu is open and I start typing the desired result is not achieved, I can see the search works and the menu data gets filtered accordingly but the Main item doesn't expand as I expected it would when setting the prop showChild to true.

1. This is the sidebar with all the props that I am using.
![my-sidebar-menu-with-props](https://user-images.githubusercontent.com/37401848/61580406-2f218e00-ab12-11e9-8dd6-aaf5ceb5fdbb.PNG)

2. My computed property that gets triggered when I search, you can see I set the property (showSearchChilds) that sets the prop showChild to true when I am in search mode.
```
        menutItems: function menutItems()
        {
            var self = this;
            var test = this.$store.getters['login/getMenuItems'];
            var keyedItems = _.keyBy(test, function(obj)
            {
                return obj["_source"].menuname + obj["_source"].path;
            });

            var menu = self.menu;
            var search = self.search;
            var tree = {};
            var searchVal = self.searchValue || "";

            if (!searchVal)
            {
                self.showSearchChilds = false;
                var firstItems = _.cloneDeep(keyedItems) || {};
                _.forEach(firstItems, function(value,key)
                {
                    if (value["_source"].menugroup == "")
                    {
                        value["_source"].title = value["_source"].menuname;
                        value["_source"].icon = value["_source"].icon;
                        tree[value["_source"].menuname] = value["_source"];
                    }
                    else
                    {
                        value["_source"].title = value["_source"].menuname;
                        firstItems[value["_source"].menugroup + value["_source"].path]["_source"].child = firstItems[value["_source"].menugroup + value["_source"].path]["_source"].child || [];
                        firstItems[value["_source"].menugroup + value["_source"].path]["_source"].child.push(value["_source"]);
                    }
                })
            }
            else
            {
                self.showSearchChilds = true;
                var newItems = _.cloneDeep(keyedItems) || {};
                _.forEach(newItems, function(value,key)
                {
                    if (value["_source"].menugroup == "")
                    {
                        value["_source"].title = value["_source"].menuname;
                        value["_source"].icon = value["_source"].icon;
                        tree[value["_source"].menuname] = value["_source"];
                    }
                    else
                    {
                        if (value["_source"].menuname.toLowerCase().includes(searchVal.toLowerCase()) && value["_source"].windowType == "tab")
                        {
                            value["_source"].title = value["_source"].menuname;
                            newItems[value["_source"].menugroup + value["_source"].path]["_source"].child = newItems[value["_source"].menugroup + value["_source"].path]["_source"].child || [];
                            newItems[value["_source"].menugroup + value["_source"].path]["_source"].child.push(value["_source"]);

                            if (newItems[value["_source"].menugroup + value["_source"].path]["_source"].menugroup != "")
                            {
                                newItems[value["_source"].menugroup + value["_source"].path]["_source"].title = newItems[value["_source"].menugroup + value["_source"].path]["_source"].menuname;
                                newItems[newItems[value["_source"].menugroup + value["_source"].path]["_source"].menugroup + newItems[value["_source"].menugroup + value["_source"].path]["_source"].path]["_source"].child = newItems[newItems[value["_source"].menugroup + value["_source"].path]["_source"].menugroup + newItems[value["_source"].menugroup + value["_source"].path]["_source"].path]["_source"].child || [];
                                newItems[newItems[value["_source"].menugroup + value["_source"].path]["_source"].menugroup + newItems[value["_source"].menugroup + value["_source"].path]["_source"].path]["_source"].child.push(newItems[value["_source"].menugroup + value["_source"].path]["_source"]);
                            }
                        }
                    }
                });
            }

            menu = _.values(tree);
            self.menu = menu;
            return menu;
        }

```

3. My initial menu when expanding it, as you can see showChilds is set to false.
![menu-flat-list](https://user-images.githubusercontent.com/37401848/61580438-a5be8b80-ab12-11e9-86c5-598d3364bd71.PNG)

4. Example of my menu after an item is clicked/expanded.
![normal-menu-show-child-fals](https://user-images.githubusercontent.com/37401848/61580448-c555b400-ab12-11e9-9c92-f1a7fd055da5.PNG)

5. When I search the menu items update and the prop showChilds is set to true but the menu doesn't update with the new prop setting.
![what-i-actually-get](https://user-images.githubusercontent.com/37401848/61580489-0fd73080-ab13-11e9-953e-3f0d860ad898.PNG)

6. When I search you can see Administration updated (Compare against picture number 4)
![what-i-want-to-achieve](https://user-images.githubusercontent.com/37401848/61580473-ddc5ce80-ab12-11e9-86d2-3af4218bbd7a.PNG)

Any help/advice/conclusion would be much appreciated.

Thank you for an awesome component, I am looking forward to see what you did in the next releases.

Kind Regards
Wehan

**Comment by yaminncco** [comment]
new update should fix your issue, `showChild` is now reactive and child always stay open

**Comment by wehanvandermerwe** [comment]
Thanks a lot, Yaminncco! 

Have a great day.

Kind Regards
Wehan
