### ISSUE TITLE
Cannot set dynamic hidden value

### ISSUE THREAD

**Issue by netinpc** [yaminncco/vue-sidebar-menu#69]
Not able to  set Dynamic hidden value to menu item.
"hidden: this._usersRoles ? false:true"
Got _usersRoles undefined error

**Comment by yaminncco** [comment]
can you show error, you can make menu computed instead of data

**Comment by netinpc** [comment]
data() {
            return {
      _usersRoles: false,
                menu: [
                    {
                        header: true,
                        // title: 'House Master',
                        component : Logo,
                        hiddenOnCollapse: true,
                    },
                    {
                        href: { name: 'admin', params: this.companyId},
                        title: 'Admin',
                        icon: 'fa fa-user-cog',
                        hidden: this._usersRoles ? false:true
                    }
                ],



//// this._usersRoles is returned as undefined

**Comment by yaminncco** [comment]
make menu computed

**Comment by yaminncco** [comment]
closing this issue
