### ISSUE TITLE
Don't show mobile items on hover while being collapsed

### ISSUE THREAD

**Issue by maestroDever** [yaminncco/vue-sidebar-menu#70]
The project is built up with Bootstrap and I am using your sidebar. First thanks for the good work on this awesome sidebar-menu 👍 
I have applied some customized css styles as was indicated in the documentation. The sidebar menu looks pretty good when expanded. But when it comes to collapsed, hovering on sidebar items breaks the good looking.

![image](https://user-images.githubusercontent.com/48345279/63986808-47f06c80-cade-11e9-88f4-4ba6f9a11bc7.png)

As you can see on the screenshot, the icon and text are not in the center line vertically.
I think my css styles have nothing to do with it.
And the problem is since they are showing only when the mouse is over there, it's hard to inspect mobile-items in browser devtools.
Hopefully I want someone can indicate what is going wrong with it. Or please let me know how I can disable hover event on collapased sidebar. Currently there seems to be no prop for that, or is there?

Thanks again :)

**Comment by yaminncco** [comment]
does the latest update fix this issue?

**Comment by yaminncco** [comment]
i think the issue have been fixed
