### ISSUE TITLE
min-width animation for expanded state

### ISSUE THREAD

**Issue by nandi95** [yaminncco/vue-sidebar-menu#71]
Currently there is an option to set width but that falls apart when viewing on smaller screens:
https://gyazo.com/164ba240b9e4447aa20b8502b16f8a44

I can set the vsm_expanded to a min width but this causes a jumping behaviour on menu open see here:
https://gyazo.com/7e3ce98f135ca6b40e964888f77ecf8d

Can a min-width prop be set up on the component so this can be handles internally like the width with the animation staying functional?

**Comment by yaminncco** [comment]
fixed in the latest update
