### ISSUE TITLE
Use route name instead fullPath comparison

### ISSUE THREAD

**Issue by sinau123** [yaminncco/vue-sidebar-menu#72]
hello, I just want to know why you use the fullPath router comparison in the matchRoute function?

https://github.com/yaminncco/vue-sidebar-menu/blob/e7c86635dd2b25d64b82b926735c716eb39dd91c/src/mixin.js#L49

I have settings like this:
```javascript
[
 {
  href: {name: 'products'},
  title: 'Produk',
  icon: 'fas fa-tag',
  alias: '/products',
 },
 //...
 // others menu item
]
```
I have trouble when I have an URL like this:
/products?page=3
or
/products?page=10

How do I make the sidebar item active for that route?

I'm sorry for my bad english.

**Comment by yaminncco** [comment]
fullPath is used to match path and query or hash , i will think about your issue to match path only

**Comment by yaminncco** [comment]
added `exactPath` property in v4.2.0 to match path only
