### ISSUE TITLE
Collapsed on start

### ISSUE THREAD

**Issue by M-u-z-k-y** [yaminncco/vue-sidebar-menu#73]
Hi @yaminncco,

First of all thanks! I love how this sidebar works/looks. My only issue right now is that I want it to be collapsed at the start.

I'm using the following code:
https://hastebin.com/oxenutacaj.xml

Am I doing something wrong or is it not working as expected?

**Comment by M-u-z-k-y** [comment]
> Hi @yaminncco,
> 
> First of all thanks! I love how this sidebar works/looks. My only issue right now is that I want it to be collapsed at the start.
> 
> I'm using the following code:
https://hastebin.com/oxenutacaj.xml

**Comment by yaminncco** [comment]
you need to pass `collapsed` prop:
`<sidebar-menu :menu="menu" collapsed />`

**Comment by M-u-z-k-y** [comment]
Thanks @yaminncco!
