### ISSUE TITLE
Menu is not scrollable on collapse mode in small screen

### ISSUE THREAD

**Issue by yonarbel** [yaminncco/vue-sidebar-menu#76]
even in the demo do the following: 

1. Collapse the menu
2. minimize your browser height
 3. hover item and try to scroll down - you will be block due to the item of that blocking its parent's scroll
4. only if you go on the edge of the scroll bar, you will be able to scroll down since you dont trigger the item hover

**Comment by yaminncco** [comment]
is this really a problem because you can still scroll if you hover over the scrollbar, though you can lower `vsm--mobile-item` z-index to fix it

**Comment by yonarbel** [comment]
i think you didnt get me right :) 

![scrollIssue](https://user-images.githubusercontent.com/13368050/65488666-4da95a00-deb2-11e9-9526-f8e0b5b2dd26.gif)

**Comment by yonarbel** [comment]
indeed it helps to reduce the z-index, however, the issue is currently still happening in the demo, so I think it should be fixed in the project.. you want me to raise a PR ? or you wanna handle this yourself? 
let me know, ill be happy to help

**Comment by yaminncco** [comment]
PR welcome

**Comment by yaminncco** [comment]
@yonarbel  I think the latest update fix this, can you confirm
