### ISSUE TITLE
Auto open childs

### ISSUE THREAD

**Issue by dflourusso** [yaminncco/vue-sidebar-menu#8]
Open childs tree automatically if match a deep route.

**Comment by yaminncco** [comment]
added in v2.2.2

**Comment by dflourusso** [comment]
Thanks, tomorrow i will test it

**Comment by ilyen85** [comment]
Hey yaminncco!

Sorry for bumping this old issue, but can't figure out why my deeply nested sidebar item is not auto opened on page reload.

```
@router
   ...
    {
      path: '/notifications/messages',
      name: 'messages',
      meta: {requiresAuth: true}, 
      component: () => import(/* webpackChunkName: "notifications-messages" */'@/views/notifications/page_messages.vue'),
    },
    ...
```

```
@Sidebar.vue
menu: [
    ...
    {
          title: 'Notifications',
          icon: 'pe-7s-mail',
          child: [
            {
              href: '/notifications/messages',
              title: 'Messages',
            },
           ...
    ...
```
When I reload the page ("/notifications/messages"), the sidebar item is still collapsed:
https://www.dropbox.com/s/qjap0q6lwqu4lte/Screenshot%202019-05-28%2013.23.08.png?dl=0

If I open the sidebar item, I can see that it's marked as the active item:
https://www.dropbox.com/s/kgxvvpzxil96d6f/Screenshot%202019-05-28%2013.24.12.png?dl=0

I might missed something in the docs, but the auto open feature is not working for me.

Is this working only if the router is in hash mode?

Thanks!
Great work by the way, really love it!

**Comment by yaminncco** [comment]
does it work in hash mode?

**Comment by ilyen85** [comment]
sorry for taking this long, nope in hash mode it behaves the same

**Comment by yaminncco** [comment]
could you reproduce issue in a repo?

**Comment by ilyen85** [comment]
Yes I will try to reproduce it, but I can't promise to make it fast, sorry!
