### ISSUE TITLE
Duplicate presence of slot "dropdown-icon" found in the same render tree

### ISSUE THREAD

**Issue by kiril-malyhin** [yaminncco/vue-sidebar-menu#80]
Hello,
first of all, big thanks for your efforts, very cool library!

I've tried to use it and got Vue errors, when tried to use provided custom slots.

![image](https://user-images.githubusercontent.com/11473999/65887617-ebb38d80-e3a6-11e9-8834-989c173e8d38.png)

I think you should use keys inside the library to avoid such errors. Maybe I can somehow specify them by myself?

Thanks in advance!

**Comment by yaminncco** [comment]
try update vue

**Comment by kiril-malyhin** [comment]
Thanks, correct!
