### ISSUE TITLE
Usage of pro Font awesome 5 icons in sections

### ISSUE THREAD

**Issue by kiril-malyhin** [yaminncco/vue-sidebar-menu#81]
Hi,
id description there is a point "The component use Font Awesome 5 Free as default for the icons, but you can customize them using slots". I've tried to use as example "fa fa-money-bill-alt". No errors from injection. Icon is available outside your library. 
So, do you any restrictions on icons or any other ideas, why it is happening?

**Comment by yaminncco** [comment]
there's a free version for money-bill-alt
and to change the dropdown and toggle icons you can override pseudo element
```
.vsm--arrow:after {
      content: '\f105';
      font-family: 'Font Awesome 5 Free';
}
.vsm--toggle-btn:after {
      content: '\f337';
      font-family: 'Font Awesome 5 Free';
}
```
or you can use slot

**Comment by kiril-malyhin** [comment]
Fixed by setup attributes
`, icon: { 
     element: 'fa', attributes: { icon: ['far', 'money-bill-alt'] } 
}`
