### ISSUE TITLE
Custom icon example

### ISSUE THREAD

**Issue by balbinott** [yaminncco/vue-sidebar-menu#84]
Hello, im trying to use fortawesome locally (custom icon) but i can't figure how to do it...
If you could help i really apreciate. Thanks in advance.

**Comment by AndyChuang1** [comment]
use the custom icon example as below
```
// import your local icon
import sunnyIcon from '@/assets/sunny-small.svg';
export default {
  data() {
    return {
      menu: [
        {
          header: true,
          title: 'Main Navigation',
          hiddenOnCollapse: true,
        },
        {
          href: { path: '/' },
          title: 'Home',
          icon: {
           //adjust element
            element: 'img',
            attributes: { src: sunnyIcon },
          },
        },
      ],
    };
  },
};
```

**Comment by balbinott** [comment]
Thanks Andy, and thanks for the component, great work!

**Comment by pnavarretec01** [comment]
> 
Nice!!! It work for me!! thanks!!

**Comment by pnavarretec01** [comment]
> use the custom icon example as below
> 
> ```
> // import your local icon
> import sunnyIcon from '@/assets/sunny-small.svg';
> export default {
>   data() {
>     return {
>       menu: [
>         {
>           header: true,
>           title: 'Main Navigation',
>           hiddenOnCollapse: true,
>         },
>         {
>           href: { path: '/' },
>           title: 'Home',
>           icon: {
>            //adjust element
>             element: 'img',
>             attributes: { src: sunnyIcon },
>           },
>         },
>       ],
>     };
>   },
> };
> ```


can you give a .selected attribute or change the icon when selected?
