### ISSUE TITLE
use regex in alias prop

### ISSUE THREAD

**Issue by sinau123** [yaminncco/vue-sidebar-menu#85]
I can use array of string in alias props, but in some scenario I need regex to match in alias. ex:
I have product list route with path: `'/products'`
```javascript
href: '/products',
title: 'Produk',
icon: 'fas fa-tag',
exactPath: true,
```

and then I want these path: `/product/1`, `/product/2` and so on as alias.
It is will be nice if we can use regex in alias prop like this:
```javascript
href: '/products',
title: 'Produk',
icon: 'fas fa-tag',
exactPath: true,
alias:'\/product\/\d+'
```

**Comment by yaminncco** [comment]
regexp support will be implemented in the future

**Comment by yaminncco** [comment]
regexp is now supported in v4.4.0
