### ISSUE TITLE
Rotating toggle button icon

### ISSUE THREAD

**Issue by adam-godfrey** [yaminncco/vue-sidebar-menu#88]
This isn't really an issue but a feature request.

Would it be possible (I have tried and failed) for he btn-toggle to have an arrow icon pointing right when collapsed and when expanded, animate it 180 degrees to point left. When it's closed again rotate it back

**Comment by yaminncco** [comment]
you can use `vsm_expanded` or `vsm_collapsed` class to rotate the icon

```
.v-sidebar-menu .vsm--toggle-btn:after {
  content: '\f105';
  font-family: 'Font Awesome 5 Free';
  display: inline-block;
}
.v-sidebar-menu.vsm_expanded .vsm--toggle-btn:after {
  transform: rotate(180deg);
}
```
