### ISSUE TITLE
Links are not updated as expected on collapsed mode

### ISSUE THREAD

**Issue by aventrax** [yaminncco/vue-sidebar-menu#93]
Hello,

My sidebar's menu item is a computed property because some links are dynamically created using a variable on my $store.

The problem is:

An entry has children, one of those is a component with a select box which is used to change the variable on the $store, the other "brothers" on the same level has links depending on the variable.

Using the select box to change the variable should update the links, and this is working when the sidebar is expanded, but **not in collapsed mode**. It is sufficient to move the mouse away and come back and the links are getting updated regulary, but as a user, this is not feasible.

Is it a bug? Can it be "fixed" or should I exclude the collapsed mode?

Many thanks for your help and this nice component!

**Comment by aventrax** [comment]
To be clear this is my menu:

![image](https://user-images.githubusercontent.com/6949472/68315527-2ef4d080-00b8-11ea-8ada-e6936af4133a.png)

The child menu containing the select box stays open when I select an entry, the computed property containing menu's items get correctly updated, it's only something on the HTML containing links relative to the old selected entry. I tried to update the component with a :key changing it with the onItemClick functions but it does not produce any effect.

With che expanded sidebar everything works, I suppose because the submenu is not "locking" the component somehow. With the collapsed sidebar it does not refresh until it loses focus. It seems enough to go on the parent entry and go back just moving the mouse.

**Comment by yaminncco** [comment]
fixed in v4.4.2 can you confirm

**Comment by aventrax** [comment]
Solved, great!
Thank you for your work! Very appreciated.
