### ISSUE TITLE
How to add icon in item child? 

### ISSUE THREAD

**Issue by ardasatata** [yaminncco/vue-sidebar-menu#94]
I tried to add an icon on children item but it won't show up on the child item, but it's showed on the parent item

```
  {
    title: 'Pelanggan',
    href: '/customer/',
    icon: 'icon-customer',
    child: [
      {
        href: '/customer/add',
        title: 'Tambah Pelanggan',
        icon: 'icon-customer'
      }
    ]
  },
```

![image](https://user-images.githubusercontent.com/17568508/69614816-62e36600-1066-11ea-9057-7252f8c68af8.png)

Can someone tell me how to add an icon on child item? 
thank you!

**Comment by yaminncco** [comment]
does the icon show in DOM? I need more details a reproduction is helpful

**Comment by ardasatata** [comment]
woops sorry my bad it's because I implement my icon with background
```
.icon-customer {
  content: '';
  display: inline-block;
  background-image: url(../svg/pelanggan.svg);
  background-repeat: no-repeat;
  vertical-align: middle;
}
```
I changed it to content and it showed up normally 
```
.icon-customer {
  content: url(../svg/pelanggan.svg);
}
```
![image](https://user-images.githubusercontent.com/17568508/69910001-94797a00-1436-11ea-9ff3-88a044ad2996.png)
