### ISSUE TITLE
Can you add typescript definitions?

### ISSUE THREAD

**Issue by deeprobin** [yaminncco/vue-sidebar-menu#95]

**Comment by yaminncco** [comment]
i am not familiar with typescript so can't implement for now, PR is welcome

**Comment by DeepRobin** [comment]
Okay, maybe i will make a pr. But TypeScript is cool :smile:

**Comment by D4RKAR117** [comment]
Hello, i make a simple type definition for this, something like that works to me 
```ts
declare module 'vue-sidebar-menu' {
	import Vue from 'vue';
	class SidebarMenu extends Vue {}
	export default SidebarMenu;
	export { SidebarMenu };
}
```

this can be complemented :D, i hope to be useful

**Comment by DeepRobin** [comment]
@D4RKAR117 Thank you, that'll help. I may pr that (or you if you want)

**Comment by D4RKAR117** [comment]
@DeepRobin im glad of help, you can make a pr but this maybe needs  many improves to acomplish a good type definitions but i think its a good start

**Comment by SqrtMinusOne** [comment]
Even defining it as 'any' would be better than nothing, because otherwise is it necessary to permit implicit any, import the module with `require` or to provide dummy definitions like @D4RKAR117 ones.

**Comment by D4RKAR117** [comment]
I already have a semi properly typed file,  anyone can review this? 

```ts
declare module 'vue-sidebar-menu' {
	import Vue from 'vue';
	interface SidebarItem {
		href: String | Object;

		title: String;

		icon: String | Object;

		badge: String | Object | undefined;

		child: Array<SidebarItem> | undefined;

		disabled: Boolean | undefined;

		class: String | undefined;

		attributes: Object | undefined;

		exactPath: Boolean | undefined;

		alias: String | Array<Object> | undefined;

		hidden: Boolean | undefined;

		hiddenOnCollapse: Boolean | undefined;
	}

	interface SidebarHeaderItem {
		header: true;

		title: String;

		hidden: Boolean | undefined;

		hiddenOnCollapse: Boolean | undefined;

		class: String | undefined;

		attributes: Object | undefined;
	}

	interface SidebarComponentItem {
		component: String;

		props: Object | undefined;

		hidden: Boolean | undefined;

		hiddenOnCollapse: Boolean | undefined;
	}

	class SidebarMenu extends Vue {
		/**
		 * List of Items in the menu
		 * Follow https://github.com/yaminncco/vue-sidebar-menu#item-properties
		 */
		menu: Array<SidebarItem | SidebarComponentItem | SidebarHeaderItem>;

		/**
		 * Sidebar Collapse state.
		 * by default false
		 */
		collapsed: Boolean | undefined;

		/**
		 * Sidebar width (expanded).
		 * by default 350px
		 */
		width: String | undefined;

		/**
		 * Sidebar width (collapsed).
		 *  by default 50px
		 */
		widthCollapsed: String | undefined;

		/**
		 * Keep only one child opened at a time (first level only).
		 * by default false
		 */
		showOneChild: Boolean | undefined;

		/**
		 * Keep all child open.
		 * by default false
		 */
		showChild: Boolean | undefined;

		/**
		 * Position sidebar right to left.
		 * by default false
		 */
		rtl: Boolean | undefined;

		/**
		 * Make sidebar relative to the parent (by default the sidebar is relative to the viewport).
		 * by default false
		 */
		relative: Boolean | undefined;

		/**
		 * Hide toggle collapse button.
		 * by default false.
		 */
		hideToggle: Boolean | undefined;

		/**
		 * Sidebar theme (available themes: 'white-theme').
		 *
		 */
		theme: String | undefined;

		/**
		 * Disable hover on collapse mode.
		 * by default false.
		 */
		disableHover: Boolean | undefined;
	}
	export { SidebarMenu };
	export default SidebarMenu;
}

```

**Comment by SqrtMinusOne** [comment]
[Optional parameters](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters) can be written like
```typescript
badge?: String | Object
```
instead of
```typescript
badge: String | Object | undefined;
```
Or it may make more sense to add default variables from [here](https://github.com/yaminncco/vue-sidebar-menu/blob/master/src/components/SidebarMenu.vue) like
```typescript
collapsed: boolean = false
```
Btw, it is [recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types) to use `boolean` and `string` (treated as a primitive type) instead of `Boolean` and `String` (treated as object)

Also, I'd add
```typescript
interface Icon {
  element: string
  class: string
  attributes?: any
  text?: any
}
```
instead of `Object` for `Icon` and `Badge`

**Comment by D4RKAR117** [comment]
> [Optional parameters](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters) can be written like
> 
> ```ts
> badge?: string | Object
> ```
> 
> instead of
> 
> ```ts
> badge: string | Object | undefined;
> ```
> 
> Or it may make more sense to add default variables from [here](https://github.com/yaminncco/vue-sidebar-menu/blob/master/src/components/SidebarMenu.vue) like
> 
> ```ts
> collapsed: boolean = false
> ```
> 
> Btw, it is [recommended](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#general-types) to use `boolean` and `string` (treated as a primitive type) instead of `Boolean` and `String` (treated as object)
> 
> Also, I'd add
> 
> ```ts
> interface Icon {
>   element: string
>   class: string
>   attributes?: any
>   text?: any
> }
> ```
> 
> instead of `Object` for `Icon` and `Badge`

Huuumm the optional parameters i already tested like that but my debbuger throwme as a mandatory attribute, I did not want to destroy the modularity or flexibility of the components, maybe you have to test it further. On the other hand I understand the wapper Class and it is really stupid to use them, thanks for the clarification.

**Comment by yaminncco** [comment]
added in v4.5.1
