### ISSUE TITLE
Font awesome not showing 

### ISSUE THREAD

**Issue by nddq** [yaminncco/vue-sidebar-menu#96]
I tried to use Font Awesome icons but they doesn't showed up. Can someone help me?

App.vue
![image](https://user-images.githubusercontent.com/28567936/69744520-5581b680-110e-11ea-9df7-8fd2568fe595.png)

main.js
![image](https://user-images.githubusercontent.com/28567936/69744598-7a762980-110e-11ea-9743-94f729b69a4f.png)

**Comment by tupham9506** [comment]
Hi. I had same problem. If you use google dev tool to inspect, you can see:
<img width="1679" alt="Screen Shot 2019-11-28 at 4 14 31 PM" src="https://user-images.githubusercontent.com/30684755/69793151-79bac180-11fa-11ea-93d9-e42a56942dc6.png">

"vue-sidebar-menu" use classes to show icons. Classes use font-family are 'Font Awesome 5 Free'.
So you must import "fontawsome style" to your project. 
Download style here: https://use.fontawesome.com/releases/v5.0.1/css/all.css.

It work for me.
![image](https://user-images.githubusercontent.com/30684755/69793552-475d9400-11fb-11ea-954d-3f20ef332554.png).

Sorry. My English isn't good.

**Comment by yaminncco** [comment]
your using vue-fontawesome here an example:

```
import Vue from 'vue'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faUserSecret } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

library.add(faUserSecret)
Vue.component('font-awesome-icon', FontAwesomeIcon)
```

```
// menu
{
  href: '/',
  title: 'Homepage',
  // custom icon:
  icon: {
    element: 'font-awesome-icon',
    attributes: {
      // icon props:
      icon: 'user-secret'
    }
  }
}
```

for toggle and dropdown icon use slots

**Comment by tupham9506** [comment]
@yaminncco thank you.

**Comment by nddq** [comment]
@yaminncco can you elaborate more on how I use slots for the toggle and dropdown icon?

**Comment by yaminncco** [comment]
```
<sidebar-menu>
  <font-awesome-icon slot="toggle-icon" icon="user-secret"></font-awesome-icon>
  <font-awesome-icon slot="dropdown-icon" icon="user-secret"></font-awesome-icon>
</sidebar-menu>
```

**Comment by godshades** [comment]
@yaminncco hi, I try 'user-secret' => can display
but when I change to 'home' => not display
what am I wrong here
